"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.buildResolveClaimInput = buildResolveClaimInput;
exports.resolveFishingClaimFromContext = resolveFishingClaimFromContext;
// AUTO-GENERATED by sync-fishing-module.js — do not edit by hand.
const rodFishingAccess_1 = require("./progression/rodFishingAccess");
const castMapping_1 = require("./castMapping");
const encounterEngine_1 = require("./encounterEngine");
function buildResolveClaimInput(ctx) {
  const rodId = (0, castMapping_1.uiRodIdToDomain)(ctx.rodUiId);
  const baitTier = (0, castMapping_1.uiBaitIdToTier)(ctx.baitUiId);
  const filteredCatalog = (0, rodFishingAccess_1.filterCreaturesByRodPermission)(
    rodId,
    ctx.creatureCatalog,
  );
  return {
    claimId: ctx.claimId,
    encounterId: ctx.encounterId,
    userId: ctx.userId,
    castId: ctx.castId,
    rodId,
    baitTier,
    currentWonderAtClaim: ctx.currentWonderAtClaim,
    caughtIds: ctx.caughtIds,
    creatureCatalog: filteredCatalog,
    now: ctx.now,
  };
}
function resolveFishingClaimFromContext(ctx) {
  return (0, encounterEngine_1.resolveFishingClaim)(buildResolveClaimInput(ctx));
}
