"use strict";
// AUTO-GENERATED by sync-fishing-module.js — do not edit by hand.
/**
 * Cast timing — single source of truth for duration + cancel grace/rate limits.
 * Cloud Functions sync via functions/scripts/sync-fishing-module.js.
 * Client imports this module for display timing only; server enforces.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CANCEL_CAST_RATE_WINDOW_MS =
  exports.CANCEL_CAST_MAX_PER_WINDOW =
  exports.CANCEL_CAST_GRACE_MS =
  exports.CAST_DURATION_MS =
    void 0;
/** Production cast wait (2 hours). Keep client FISHING_CAST_DURATION_MS in sync. */
exports.CAST_DURATION_MS = 2 * 60 * 60 * 1000;
/** Quiet cancel window after cast create — server-enforced against createdAt. */
exports.CANCEL_CAST_GRACE_MS = 15_000;
/** Max successful cancels per rolling window (anti cast+cancel cycling). */
exports.CANCEL_CAST_MAX_PER_WINDOW = 3;
exports.CANCEL_CAST_RATE_WINDOW_MS = 60 * 60 * 1000;
