"use strict";
// AUTO-GENERATED by sync-progression-module.js — do not edit by hand.
/** Pure domain types for the Sanctuary fishing economy. Server-sync friendly. */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DEFAULT_FISHING_PITY = exports.ROD_CRAFT_DURATION_MS = void 0;
exports.ROD_CRAFT_DURATION_MS = 3 * 24 * 60 * 60 * 1000;
exports.DEFAULT_FISHING_PITY = {
  consecutiveChanceMisses: 0,
  epicTopRareDryStreak: {},
};
