"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.evaluateCraftableStates = evaluateCraftableStates;
exports.mergeEvaluateResult = mergeEvaluateResult;
exports.lessonProgressFromCompletedMap = lessonProgressFromCompletedMap;
// AUTO-GENERATED by sync-progression-module.js — do not edit by hand.
const craftCosts_1 = require("./craftCosts");
const partsAwards_1 = require("./partsAwards");
const moduleRodMap_1 = require("./moduleRodMap");
const subscriptionCraftGate_1 = require("./subscriptionCraftGate");
const craftStates_1 = require("./craftStates");
const ALL_PROGRESSION_ROD_IDS = [
  ...moduleRodMap_1.RARE_ELEMENT_ROD_IDS,
  moduleRodMap_1.WILDCARD_ROD_ID,
  ...moduleRodMap_1.EPIC_ELEMENT_ROD_IDS,
];
function defaultPlayerRod(rodId) {
  return {
    rodId,
    state: "locked",
    craftStartedAt: null,
    craftCompletedAt: null,
    wonderInvested: 0,
    partsSpentOnCraft: 0,
    sourceModule: (0, moduleRodMap_1.moduleIdForRareRod)(rodId),
    giftSource: null,
  };
}
function getRodRecord(playerRods, rodId) {
  return playerRods[rodId] ?? defaultPlayerRod(rodId);
}
function hasSufficientBalances(rodId, inventory) {
  const cost = (0, craftCosts_1.getCraftCost)(rodId);
  return inventory.parts >= cost.parts && inventory.storedWonder >= cost.storedWonder;
}
function allFourRareRodsInHand(playerRods) {
  return moduleRodMap_1.RARE_ELEMENT_ROD_IDS.every((rodId) =>
    (0, craftStates_1.isRodInHand)(getRodRecord(playerRods, rodId).state),
  );
}
function evaluateRareRodCraftable(rodId, input) {
  const moduleId = (0, moduleRodMap_1.moduleIdForRareRod)(rodId);
  if (moduleId == null) return false;
  if (!(0, subscriptionCraftGate_1.canCraftRodBySubscription)(rodId, input.subscriptionTier))
    return false;
  if (!(0, partsAwards_1.isModuleClusterComplete)(input.lessonProgress, moduleId)) return false;
  return hasSufficientBalances(rodId, input.inventory);
}
function evaluateEpicRodCraftable(rodId, input) {
  const rareId = (0, moduleRodMap_1.rareRodForEpic)(rodId);
  if (rareId == null) return false;
  if (!(0, subscriptionCraftGate_1.canCraftRodBySubscription)(rodId, input.subscriptionTier))
    return false;
  if (!(0, partsAwards_1.allLessonsComplete)(input.lessonProgress)) return false;
  if (!(0, craftStates_1.isRodInHand)(getRodRecord(input.playerRods, rareId).state)) return false;
  return hasSufficientBalances(rodId, input.inventory);
}
function evaluateTargetState(rodId, input, now) {
  const current = getRodRecord(input.playerRods, rodId);
  if (current.state === "equipped") {
    return "equipped";
  }
  if (current.state === "crafting") {
    if ((0, craftCosts_1.isCraftTimerComplete)(rodId, current.craftStartedAt, now)) {
      return "ready";
    }
    return "crafting";
  }
  if (rodId === moduleRodMap_1.WILDCARD_ROD_ID) {
    if (current.state === "ready") {
      return "ready";
    }
    if (allFourRareRodsInHand(input.playerRods)) {
      return "ready";
    }
    return "locked";
  }
  if (current.state === "ready") {
    return "ready";
  }
  const isRare = moduleRodMap_1.RARE_ELEMENT_ROD_IDS.includes(rodId);
  const isEpic = moduleRodMap_1.EPIC_ELEMENT_ROD_IDS.includes(rodId);
  const craftable = isRare
    ? evaluateRareRodCraftable(rodId, input)
    : isEpic
      ? evaluateEpicRodCraftable(rodId, input)
      : false;
  return craftable ? "craftable" : "locked";
}
/**
 * Pure progression evaluation — shared by server and client (read-only hints on client).
 * Firestore remains source of truth; server applies transitions transactionally.
 */
function evaluateCraftableStates(input) {
  const now = input.now ?? Date.now();
  const transitions = [];
  const rodUnlocked = [];
  let wildcardGifted = false;
  for (const rodId of ALL_PROGRESSION_ROD_IDS) {
    const current = getRodRecord(input.playerRods, rodId);
    const next = evaluateTargetState(rodId, input, now);
    if (current.state === next) continue;
    // Never downgrade active craft progress.
    if (current.state === "crafting" && next === "locked") continue;
    if (current.state === "ready" && next === "locked") continue;
    if (current.state === "craftable" && next === "locked") continue;
    const reason =
      rodId === moduleRodMap_1.WILDCARD_ROD_ID && next === "ready"
        ? "journey_gift"
        : next === "craftable"
          ? "prerequisites_met"
          : next === "ready" && current.state === "crafting"
            ? "craft_timer_complete"
            : "progression_update";
    transitions.push({ rodId, from: current.state, to: next, reason });
    if (next === "craftable" && current.state === "locked") {
      rodUnlocked.push(rodId);
    }
    if (
      rodId === moduleRodMap_1.WILDCARD_ROD_ID &&
      next === "ready" &&
      current.state === "locked"
    ) {
      wildcardGifted = true;
    }
  }
  return { transitions, rodUnlocked, wildcardGifted };
}
function mergeEvaluateResult(playerRods, result, now = Date.now()) {
  const next = { ...playerRods };
  for (const transition of result.transitions) {
    const existing = getRodRecord(next, transition.rodId);
    const patch = {
      ...existing,
      state: transition.to,
    };
    if (transition.to === "ready" && transition.from === "crafting") {
      patch.craftCompletedAt = now;
    }
    if (
      transition.rodId === moduleRodMap_1.WILDCARD_ROD_ID &&
      transition.to === "ready" &&
      transition.reason === "journey_gift"
    ) {
      patch.giftSource = "journey_gift";
    }
    next[transition.rodId] = patch;
  }
  return next;
}
/** Legacy `completedLessons` map → lesson progress records for evaluation. */
function lessonProgressFromCompletedMap(completedLessons) {
  return Object.fromEntries(
    Object.entries(completedLessons).map(([lessonId, completed]) => [
      lessonId,
      { lessonId, completed, completedAt: null, lastOpenedAt: null },
    ]),
  );
}
