"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.filterCreaturesByRodPermission = void 0;
exports.assertRodOwnedForCast = assertRodOwnedForCast;
// AUTO-GENERATED by sync-fishing-module.js — do not edit by hand.
var rodFishingAccess_1 = require("./rodFishingAccess");
Object.defineProperty(exports, "filterCreaturesByRodPermission", {
  enumerable: true,
  get: function () {
    return rodFishingAccess_1.filterCreaturesByRodPermission;
  },
});
function assertRodOwnedForCast(rodId, state) {
  if (state !== "ready" && state !== "equipped") {
    throw new Error(`Rod ${rodId} is not owned for fishing`);
  }
}
