"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.REVISIT_MIN_DAYS =
  exports.CLUSTER_COMPLETION_BONUS =
  exports.REVISIT_BONUS_PARTS =
  exports.DIARY_COMPLETION_PARTS =
    void 0;
exports.isLessonCompleted = isLessonCompleted;
exports.moduleIdForLesson = moduleIdForLesson;
exports.isModuleClusterComplete = isModuleClusterComplete;
exports.allLessonsComplete = allLessonsComplete;
exports.computePartsAwardForLessonCompletion = computePartsAwardForLessonCompletion;
// AUTO-GENERATED by sync-progression-module.js — do not edit by hand.
const moduleRodMap_1 = require("./moduleRodMap");
exports.DIARY_COMPLETION_PARTS = 1;
exports.REVISIT_BONUS_PARTS = 1;
exports.CLUSTER_COMPLETION_BONUS = 5;
exports.REVISIT_MIN_DAYS = 7;
const MS_PER_DAY = 24 * 60 * 60 * 1000;
function isLessonCompleted(lessonProgress, lessonId) {
  const entry = lessonProgress[lessonId];
  if (typeof entry === "boolean") return entry;
  return entry?.completed === true;
}
function moduleIdForLesson(lessonId) {
  const [moduleRaw] = lessonId.split(".");
  const moduleId = Number(moduleRaw);
  return Number.isFinite(moduleId) ? moduleId : null;
}
function isModuleClusterComplete(lessonProgress, moduleId) {
  const lessonIds = moduleRodMap_1.MODULE_LESSON_IDS[moduleId];
  if (!lessonIds?.length) return false;
  return lessonIds.every((lessonId) => isLessonCompleted(lessonProgress, lessonId));
}
function allLessonsComplete(lessonProgress) {
  return moduleRodMap_1.ALL_LESSON_IDS.every((lessonId) =>
    isLessonCompleted(lessonProgress, lessonId),
  );
}
function computePartsAwardForLessonCompletion(input) {
  const { lessonId, lessonProgress, now = Date.now(), alreadyCompleted = false } = input;
  if (alreadyCompleted || isLessonCompleted(lessonProgress, lessonId)) {
    return {
      base: 0,
      revisitBonus: 0,
      clusterBonus: 0,
      total: 0,
      wasRevisit: false,
      clusterCompleted: false,
      clusterModuleId: null,
    };
  }
  const moduleId = moduleIdForLesson(lessonId);
  const clusterWasComplete =
    moduleId != null ? isModuleClusterComplete(lessonProgress, moduleId) : false;
  let revisitBonus = 0;
  let wasRevisit = false;
  const prior = lessonProgress[lessonId];
  if (prior && typeof prior !== "boolean" && prior.completedAt != null) {
    const daysSince = (now - prior.completedAt) / MS_PER_DAY;
    if (daysSince >= exports.REVISIT_MIN_DAYS) {
      revisitBonus = exports.REVISIT_BONUS_PARTS;
      wasRevisit = true;
    }
  }
  const clusterBonus =
    moduleId != null && !clusterWasComplete
      ? willCompleteModuleCluster(lessonProgress, lessonId)
        ? exports.CLUSTER_COMPLETION_BONUS
        : 0
      : 0;
  const base = exports.DIARY_COMPLETION_PARTS;
  const total = base + revisitBonus + clusterBonus;
  return {
    base,
    revisitBonus,
    clusterBonus,
    total,
    wasRevisit,
    clusterCompleted: clusterBonus > 0,
    clusterModuleId: clusterBonus > 0 ? moduleId : null,
  };
}
function willCompleteModuleCluster(lessonProgress, completingLessonId) {
  const moduleId = moduleIdForLesson(completingLessonId);
  if (moduleId == null) return false;
  const lessonIds = moduleRodMap_1.MODULE_LESSON_IDS[moduleId];
  if (!lessonIds?.length) return false;
  return lessonIds.every(
    (lessonId) => lessonId === completingLessonId || isLessonCompleted(lessonProgress, lessonId),
  );
}
