// AUTO-GENERATED by sync-well-module.js — do not edit by hand.
/** Auto-generated by scripts/generate_well_catalog.py — do not edit by hand. */

import type { WellBankQuestion } from "./types";

export const WELL_QUESTIONS_6_12: WellBankQuestion[] = [
  {
    questionId: "curiosity-6-12-001",
    category: "curiosity",
    ageBand: "6-12",
    themeLabel: "Wondering About...",
    prompt:
      "If you could spend an entire week becoming an expert on one weird topic, what would you choose?",
    depthRating: 3,
    whyThisMatters:
      "Children often reveal interests long before adults notice them. This teaches parents how to listen.",
  },
  {
    questionId: "curiosity-6-12-002",
    category: "curiosity",
    ageBand: "6-12",
    themeLabel: "Wondering About...",
    prompt: "Is there a question about how your own body works that you've never asked anyone?",
    depthRating: 3,
    whyThisMatters:
      "Children often reveal interests long before adults notice them. This teaches parents how to listen.",
  },
  {
    questionId: "curiosity-6-12-003",
    category: "curiosity",
    ageBand: "6-12",
    themeLabel: "Wondering About...",
    prompt:
      "If you could secretly watch how something is made — any factory, kitchen, or workshop — which would you pick?",
    depthRating: 3,
    whyThisMatters:
      "Children often reveal interests long before adults notice them. This teaches parents how to listen.",
  },
  {
    questionId: "curiosity-6-12-004",
    category: "curiosity",
    ageBand: "6-12",
    themeLabel: "Wondering About...",
    prompt: "What's something you've always wanted to try just once, even if it seems small?",
    depthRating: 3,
    whyThisMatters:
      "Children often reveal interests long before adults notice them. This teaches parents how to listen.",
  },
  {
    questionId: "curiosity-6-12-005",
    category: "curiosity",
    ageBand: "6-12",
    themeLabel: "Wondering About...",
    prompt:
      "If you could ask a tree what it's seen over its lifetime, what do you think it would say?",
    depthRating: 3,
    whyThisMatters:
      "Children often reveal interests long before adults notice them. This teaches parents how to listen.",
  },
  {
    questionId: "curiosity-6-12-006",
    category: "curiosity",
    ageBand: "6-12",
    themeLabel: "Wondering About...",
    prompt:
      "Is there a number, pattern, or rule you've noticed that seems to repeat everywhere once you start looking?",
    depthRating: 3,
    whyThisMatters:
      "Children often reveal interests long before adults notice them. This teaches parents how to listen.",
  },
  {
    questionId: "curiosity-6-12-007",
    category: "curiosity",
    ageBand: "6-12",
    themeLabel: "Wondering About...",
    prompt:
      "If you could have a conversation with an animal for ten minutes, which animal would give you the most surprising answers?",
    depthRating: 3,
    whyThisMatters:
      "Children often reveal interests long before adults notice them. This teaches parents how to listen.",
  },
  {
    questionId: "curiosity-6-12-008",
    category: "curiosity",
    ageBand: "6-12",
    themeLabel: "Wondering About...",
    prompt:
      "What's something adults say is 'just how it is' that you've always wanted to question?",
    depthRating: 3,
    whyThisMatters:
      "Children often reveal interests long before adults notice them. This teaches parents how to listen.",
  },
  {
    questionId: "curiosity-6-12-009",
    category: "curiosity",
    ageBand: "6-12",
    themeLabel: "Wondering About...",
    prompt:
      "If you could time-travel to watch one historical event happen — not change it, just watch — what would you pick?",
    depthRating: 3,
    whyThisMatters:
      "Children often reveal interests long before adults notice them. This teaches parents how to listen.",
  },
  {
    questionId: "curiosity-6-12-010",
    category: "curiosity",
    ageBand: "6-12",
    themeLabel: "Wondering About...",
    prompt:
      "Is there something you've taken apart, broken, or messed with just to understand it better?",
    depthRating: 3,
    whyThisMatters:
      "Children often reveal interests long before adults notice them. This teaches parents how to listen.",
  },
  {
    questionId: "curiosity-6-12-011",
    category: "curiosity",
    ageBand: "6-12",
    themeLabel: "Wondering About...",
    prompt:
      "If you could ask one question to someone from a completely different country, what would you want to know about their life?",
    depthRating: 3,
    whyThisMatters:
      "Children often reveal interests long before adults notice them. This teaches parents how to listen.",
  },
  {
    questionId: "curiosity-6-12-012",
    category: "curiosity",
    ageBand: "6-12",
    themeLabel: "Wondering About...",
    prompt: "What's a 'why' question you've had for a really long time without an answer?",
    depthRating: 3,
    whyThisMatters:
      "Children often reveal interests long before adults notice them. This teaches parents how to listen.",
  },
  {
    questionId: "curiosity-6-12-013",
    category: "curiosity",
    ageBand: "6-12",
    themeLabel: "Wondering About...",
    prompt:
      "If you could shrink down to the size of an ant for a day, what would you want to explore first?",
    depthRating: 3,
    whyThisMatters:
      "Children often reveal interests long before adults notice them. This teaches parents how to listen.",
  },
  {
    questionId: "worries-6-12-001",
    category: "worries",
    ageBand: "6-12",
    themeLabel: "Carrying Quietly...",
    prompt: "Is there something you've gotten better at hiding how you feel about?",
    depthRating: 4,
    whyThisMatters:
      "Worries named without rush lose some of their power — and show you where support is needed.",
  },
  {
    questionId: "worries-6-12-002",
    category: "worries",
    ageBand: "6-12",
    themeLabel: "Carrying Quietly...",
    prompt:
      "When you imagine next year, is there anything about it that feels uncertain or makes you wonder?",
    depthRating: 4,
    whyThisMatters:
      "Worries named without rush lose some of their power — and show you where support is needed.",
  },
  {
    questionId: "worries-6-12-003",
    category: "worries",
    ageBand: "6-12",
    themeLabel: "Carrying Quietly...",
    prompt:
      "Has there been a time you said 'I'm fine' when you weren't completely sure that was true?",
    depthRating: 4,
    whyThisMatters:
      "Worries named without rush lose some of their power — and show you where support is needed.",
  },
  {
    questionId: "worries-6-12-004",
    category: "worries",
    ageBand: "6-12",
    themeLabel: "Carrying Quietly...",
    prompt:
      "Is there a comparison you sometimes make between yourself and someone else that doesn't feel great?",
    depthRating: 4,
    whyThisMatters:
      "Worries named without rush lose some of their power — and show you where support is needed.",
  },
  {
    questionId: "worries-6-12-005",
    category: "worries",
    ageBand: "6-12",
    themeLabel: "Carrying Quietly...",
    prompt:
      "When you make a mistake in front of others, what's the hardest part about that moment?",
    depthRating: 4,
    whyThisMatters:
      "Worries named without rush lose some of their power — and show you where support is needed.",
  },
  {
    questionId: "worries-6-12-006",
    category: "worries",
    ageBand: "6-12",
    themeLabel: "Carrying Quietly...",
    prompt:
      "Is there something you used to be excited about that's started to feel like pressure instead?",
    depthRating: 4,
    whyThisMatters:
      "Worries named without rush lose some of their power — and show you where support is needed.",
  },
  {
    questionId: "worries-6-12-007",
    category: "worries",
    ageBand: "6-12",
    themeLabel: "Carrying Quietly...",
    prompt:
      "Has there been a moment where you felt like you had to grow up a little faster than you wanted to?",
    depthRating: 4,
    whyThisMatters:
      "Worries named without rush lose some of their power — and show you where support is needed.",
  },
  {
    questionId: "worries-6-12-008",
    category: "worries",
    ageBand: "6-12",
    themeLabel: "Carrying Quietly...",
    prompt: "Is there a topic that, if it comes up, makes you want to change the subject?",
    depthRating: 4,
    whyThisMatters:
      "Worries named without rush lose some of their power — and show you where support is needed.",
  },
  {
    questionId: "worries-6-12-009",
    category: "worries",
    ageBand: "6-12",
    themeLabel: "Carrying Quietly...",
    prompt:
      "When you think about things you can't control, is there one that's been on your mind lately?",
    depthRating: 4,
    whyThisMatters:
      "Worries named without rush lose some of their power — and show you where support is needed.",
  },
  {
    questionId: "worries-6-12-010",
    category: "worries",
    ageBand: "6-12",
    themeLabel: "Carrying Quietly...",
    prompt:
      "Has there been a time you felt responsible for something that maybe wasn't fully your job to fix?",
    depthRating: 4,
    whyThisMatters:
      "Worries named without rush lose some of their power — and show you where support is needed.",
  },
  {
    questionId: "worries-6-12-011",
    category: "worries",
    ageBand: "6-12",
    themeLabel: "Carrying Quietly...",
    prompt: "Is there a 'what people think of me' thought that sometimes gets loud in your head?",
    depthRating: 4,
    whyThisMatters:
      "Worries named without rush lose some of their power — and show you where support is needed.",
  },
  {
    questionId: "worries-6-12-012",
    category: "worries",
    ageBand: "6-12",
    themeLabel: "Carrying Quietly...",
    prompt: "When you're not sure how someone feels about you, what do you usually assume?",
    depthRating: 4,
    whyThisMatters:
      "Worries named without rush lose some of their power — and show you where support is needed.",
  },
  {
    questionId: "worries-6-12-013",
    category: "worries",
    ageBand: "6-12",
    themeLabel: "Carrying Quietly...",
    prompt:
      "Is there something you've decided not to try because you're worried how it might turn out?",
    depthRating: 4,
    whyThisMatters:
      "Worries named without rush lose some of their power — and show you where support is needed.",
  },
  {
    questionId: "excitement-6-12-001",
    category: "excitement",
    ageBand: "6-12",
    themeLabel: "Bright Right Now...",
    prompt:
      "If you could design a perfect weekend with zero rules, what would the schedule look like?",
    depthRating: 3,
    whyThisMatters:
      "What energizes them now often points toward strengths worth nurturing deliberately.",
  },
  {
    questionId: "excitement-6-12-002",
    category: "excitement",
    ageBand: "6-12",
    themeLabel: "Bright Right Now...",
    prompt: "Is there a skill that, if you mastered it, would feel like a really big deal to you?",
    depthRating: 3,
    whyThisMatters:
      "What energizes them now often points toward strengths worth nurturing deliberately.",
  },
  {
    questionId: "excitement-6-12-003",
    category: "excitement",
    ageBand: "6-12",
    themeLabel: "Bright Right Now...",
    prompt:
      "What's something you've gotten genuinely better at this year, even if no one's pointed it out?",
    depthRating: 3,
    whyThisMatters:
      "What energizes them now often points toward strengths worth nurturing deliberately.",
  },
  {
    questionId: "excitement-6-12-004",
    category: "excitement",
    ageBand: "6-12",
    themeLabel: "Bright Right Now...",
    prompt:
      "If you could meet your future self at age 25, what's the first thing you'd want to ask them?",
    depthRating: 3,
    whyThisMatters:
      "What energizes them now often points toward strengths worth nurturing deliberately.",
  },
  {
    questionId: "excitement-6-12-005",
    category: "excitement",
    ageBand: "6-12",
    themeLabel: "Bright Right Now...",
    prompt:
      "Is there a place in the world that, if you saw a picture of it, would make you want to go there immediately?",
    depthRating: 3,
    whyThisMatters:
      "What energizes them now often points toward strengths worth nurturing deliberately.",
  },
  {
    questionId: "excitement-6-12-006",
    category: "excitement",
    ageBand: "6-12",
    themeLabel: "Bright Right Now...",
    prompt: "What's something you do that makes you forget to check the time?",
    depthRating: 3,
    whyThisMatters:
      "What energizes them now often points toward strengths worth nurturing deliberately.",
  },
  {
    questionId: "excitement-6-12-007",
    category: "excitement",
    ageBand: "6-12",
    themeLabel: "Bright Right Now...",
    prompt:
      "If you could create an event that happens once a year just for our family, what would it be?",
    depthRating: 3,
    whyThisMatters:
      "What energizes them now often points toward strengths worth nurturing deliberately.",
  },
  {
    questionId: "excitement-6-12-008",
    category: "excitement",
    ageBand: "6-12",
    themeLabel: "Bright Right Now...",
    prompt: "Is there something you've been quietly hoping will happen, even if it's a long shot?",
    depthRating: 3,
    whyThisMatters:
      "What energizes them now often points toward strengths worth nurturing deliberately.",
  },
  {
    questionId: "excitement-6-12-009",
    category: "excitement",
    ageBand: "6-12",
    themeLabel: "Bright Right Now...",
    prompt: "What's a compliment you received that you still think about?",
    depthRating: 3,
    whyThisMatters:
      "What energizes them now often points toward strengths worth nurturing deliberately.",
  },
  {
    questionId: "excitement-6-12-010",
    category: "excitement",
    ageBand: "6-12",
    themeLabel: "Bright Right Now...",
    prompt: "If you had unlimited resources to start a project — any size — what would you make?",
    depthRating: 3,
    whyThisMatters:
      "What energizes them now often points toward strengths worth nurturing deliberately.",
  },
  {
    questionId: "excitement-6-12-011",
    category: "excitement",
    ageBand: "6-12",
    themeLabel: "Bright Right Now...",
    prompt: "Is there a 'someday' goal you have that you haven't told many people about?",
    depthRating: 3,
    whyThisMatters:
      "What energizes them now often points toward strengths worth nurturing deliberately.",
  },
  {
    questionId: "excitement-6-12-012",
    category: "excitement",
    ageBand: "6-12",
    themeLabel: "Bright Right Now...",
    prompt: "What's something that, when it happens, instantly puts you in a good mood?",
    depthRating: 3,
    whyThisMatters:
      "What energizes them now often points toward strengths worth nurturing deliberately.",
  },
  {
    questionId: "excitement-6-12-013",
    category: "excitement",
    ageBand: "6-12",
    themeLabel: "Bright Right Now...",
    prompt:
      "If you could give a tour of your favorite place to someone who'd never been there, what would you show them first?",
    depthRating: 3,
    whyThisMatters:
      "What energizes them now often points toward strengths worth nurturing deliberately.",
  },
  {
    questionId: "interests-6-12-001",
    category: "interests",
    ageBand: "6-12",
    themeLabel: "Drawn Toward...",
    prompt:
      "If you had to choose a topic to give a presentation about — something you actually find interesting — what would it be?",
    depthRating: 3,
    whyThisMatters:
      "Interests that feel 'random' to adults are often the earliest signal of identity forming.",
  },
  {
    questionId: "interests-6-12-002",
    category: "interests",
    ageBand: "6-12",
    themeLabel: "Drawn Toward...",
    prompt:
      "Is there a type of puzzle, game, or challenge that you find satisfying to work through?",
    depthRating: 3,
    whyThisMatters:
      "Interests that feel 'random' to adults are often the earliest signal of identity forming.",
  },
  {
    questionId: "interests-6-12-003",
    category: "interests",
    ageBand: "6-12",
    themeLabel: "Drawn Toward...",
    prompt: "What's something you'd want to get really good at, even if it took years?",
    depthRating: 3,
    whyThisMatters:
      "Interests that feel 'random' to adults are often the earliest signal of identity forming.",
  },
  {
    questionId: "interests-6-12-004",
    category: "interests",
    ageBand: "6-12",
    themeLabel: "Drawn Toward...",
    prompt:
      "If you could shadow someone at their job for a day, what kind of work would you want to see?",
    depthRating: 3,
    whyThisMatters:
      "Interests that feel 'random' to adults are often the earliest signal of identity forming.",
  },
  {
    questionId: "interests-6-12-005",
    category: "interests",
    ageBand: "6-12",
    themeLabel: "Drawn Toward...",
    prompt:
      "Is there a system or set of rules — like in a game, sport, or hobby — that you find genuinely interesting to understand?",
    depthRating: 3,
    whyThisMatters:
      "Interests that feel 'random' to adults are often the earliest signal of identity forming.",
  },
  {
    questionId: "interests-6-12-006",
    category: "interests",
    ageBand: "6-12",
    themeLabel: "Drawn Toward...",
    prompt: "What's something you've researched on your own just because you wanted to know more?",
    depthRating: 3,
    whyThisMatters:
      "Interests that feel 'random' to adults are often the earliest signal of identity forming.",
  },
  {
    questionId: "interests-6-12-007",
    category: "interests",
    ageBand: "6-12",
    themeLabel: "Drawn Toward...",
    prompt:
      "If you could redesign something that already exists to work better, what would you choose?",
    depthRating: 3,
    whyThisMatters:
      "Interests that feel 'random' to adults are often the earliest signal of identity forming.",
  },
  {
    questionId: "interests-6-12-008",
    category: "interests",
    ageBand: "6-12",
    themeLabel: "Drawn Toward...",
    prompt:
      "Is there a craft, art form, or skill you've seen someone do that made you think 'I want to learn that'?",
    depthRating: 3,
    whyThisMatters:
      "Interests that feel 'random' to adults are often the earliest signal of identity forming.",
  },
  {
    questionId: "interests-6-12-009",
    category: "interests",
    ageBand: "6-12",
    themeLabel: "Drawn Toward...",
    prompt: "What's a topic where you know more than most people your age?",
    depthRating: 3,
    whyThisMatters:
      "Interests that feel 'random' to adults are often the earliest signal of identity forming.",
  },
  {
    questionId: "interests-6-12-010",
    category: "interests",
    ageBand: "6-12",
    themeLabel: "Drawn Toward...",
    prompt:
      "If you had to pick a 'specialty' — something you're known for — what would you want it to be?",
    depthRating: 3,
    whyThisMatters:
      "Interests that feel 'random' to adults are often the earliest signal of identity forming.",
  },
  {
    questionId: "interests-6-12-011",
    category: "interests",
    ageBand: "6-12",
    themeLabel: "Drawn Toward...",
    prompt:
      "Is there something you do differently than how you were taught, because your way makes more sense to you?",
    depthRating: 3,
    whyThisMatters:
      "Interests that feel 'random' to adults are often the earliest signal of identity forming.",
  },
  {
    questionId: "interests-6-12-012",
    category: "interests",
    ageBand: "6-12",
    themeLabel: "Drawn Toward...",
    prompt: "What's something you've taught yourself, even informally?",
    depthRating: 3,
    whyThisMatters:
      "Interests that feel 'random' to adults are often the earliest signal of identity forming.",
  },
  {
    questionId: "emotional-6-12-001",
    category: "emotional",
    ageBand: "6-12",
    themeLabel: "Feeling Both Ways...",
    prompt: "Is there a feeling that's grown stronger as you've gotten older?",
    depthRating: 4,
    whyThisMatters:
      "Understanding their emotional patterns helps you respond to the feeling, not just the behavior.",
  },
  {
    questionId: "emotional-6-12-002",
    category: "emotional",
    ageBand: "6-12",
    themeLabel: "Feeling Both Ways...",
    prompt: "When you're disappointed, how long does it usually take before you feel okay again?",
    depthRating: 4,
    whyThisMatters:
      "Understanding their emotional patterns helps you respond to the feeling, not just the behavior.",
  },
  {
    questionId: "emotional-6-12-003",
    category: "emotional",
    ageBand: "6-12",
    themeLabel: "Feeling Both Ways...",
    prompt: "Has there been a time you felt proud of how you handled a hard feeling?",
    depthRating: 4,
    whyThisMatters:
      "Understanding their emotional patterns helps you respond to the feeling, not just the behavior.",
  },
  {
    questionId: "emotional-6-12-004",
    category: "emotional",
    ageBand: "6-12",
    themeLabel: "Feeling Both Ways...",
    prompt:
      "Is there something that used to upset you that doesn't anymore — and do you know why that changed?",
    depthRating: 4,
    whyThisMatters:
      "Understanding their emotional patterns helps you respond to the feeling, not just the behavior.",
  },
  {
    questionId: "emotional-6-12-005",
    category: "emotional",
    ageBand: "6-12",
    themeLabel: "Feeling Both Ways...",
    prompt: "When you feel overwhelmed, what does that actually feel like for you?",
    depthRating: 4,
    whyThisMatters:
      "Understanding their emotional patterns helps you respond to the feeling, not just the behavior.",
  },
  {
    questionId: "emotional-6-12-006",
    category: "emotional",
    ageBand: "6-12",
    themeLabel: "Feeling Both Ways...",
    prompt: "Is there a difference between how you act when you're upset and how you feel inside?",
    depthRating: 4,
    whyThisMatters:
      "Understanding their emotional patterns helps you respond to the feeling, not just the behavior.",
  },
  {
    questionId: "emotional-6-12-007",
    category: "emotional",
    ageBand: "6-12",
    themeLabel: "Feeling Both Ways...",
    prompt:
      "Has there been a moment where you felt calm in a situation that usually makes you anxious?",
    depthRating: 4,
    whyThisMatters:
      "Understanding their emotional patterns helps you respond to the feeling, not just the behavior.",
  },
  {
    questionId: "emotional-6-12-008",
    category: "emotional",
    ageBand: "6-12",
    themeLabel: "Feeling Both Ways...",
    prompt: "When you think back on a hard day, what usually helped, even a little?",
    depthRating: 4,
    whyThisMatters:
      "Understanding their emotional patterns helps you respond to the feeling, not just the behavior.",
  },
  {
    questionId: "emotional-6-12-009",
    category: "emotional",
    ageBand: "6-12",
    themeLabel: "Feeling Both Ways...",
    prompt: "Is there an emotion you wish you understood better — in yourself or in other people?",
    depthRating: 4,
    whyThisMatters:
      "Understanding their emotional patterns helps you respond to the feeling, not just the behavior.",
  },
  {
    questionId: "emotional-6-12-010",
    category: "emotional",
    ageBand: "6-12",
    themeLabel: "Feeling Both Ways...",
    prompt:
      "Has there been a time your feelings surprised you — stronger or different than you expected?",
    depthRating: 4,
    whyThisMatters:
      "Understanding their emotional patterns helps you respond to the feeling, not just the behavior.",
  },
  {
    questionId: "emotional-6-12-011",
    category: "emotional",
    ageBand: "6-12",
    themeLabel: "Feeling Both Ways...",
    prompt:
      "When you're feeling a lot of different things at once, how do you usually sort through it?",
    depthRating: 4,
    whyThisMatters:
      "Understanding their emotional patterns helps you respond to the feeling, not just the behavior.",
  },
  {
    questionId: "emotional-6-12-012",
    category: "emotional",
    ageBand: "6-12",
    themeLabel: "Feeling Both Ways...",
    prompt: "Is there something that makes you feel instantly calmer when things feel chaotic?",
    depthRating: 4,
    whyThisMatters:
      "Understanding their emotional patterns helps you respond to the feeling, not just the behavior.",
  },
  {
    questionId: "emotional-6-12-013",
    category: "emotional",
    ageBand: "6-12",
    themeLabel: "Feeling Both Ways...",
    prompt:
      "Has there been a time you felt proud of someone else's feelings — like seeing them handle something well?",
    depthRating: 4,
    whyThisMatters:
      "Understanding their emotional patterns helps you respond to the feeling, not just the behavior.",
  },
  {
    questionId: "social-6-12-001",
    category: "social",
    ageBand: "6-12",
    themeLabel: "Between People...",
    prompt: "Is there a friendship that's changed a lot over the years — for better or different?",
    depthRating: 3,
    whyThisMatters:
      "Social choices at this age preview the relational skills they'll carry into adolescence.",
  },
  {
    questionId: "social-6-12-002",
    category: "social",
    ageBand: "6-12",
    themeLabel: "Between People...",
    prompt:
      "When you're with different groups of friends, do you feel like a different version of yourself with each?",
    depthRating: 3,
    whyThisMatters:
      "Social choices at this age preview the relational skills they'll carry into adolescence.",
  },
  {
    questionId: "social-6-12-003",
    category: "social",
    ageBand: "6-12",
    themeLabel: "Between People...",
    prompt:
      "Has there been a time you had to choose between what a friend wanted and what felt right to you?",
    depthRating: 3,
    whyThisMatters:
      "Social choices at this age preview the relational skills they'll carry into adolescence.",
  },
  {
    questionId: "social-6-12-004",
    category: "social",
    ageBand: "6-12",
    themeLabel: "Between People...",
    prompt: "Is there someone you've never really talked to but think you might get along with?",
    depthRating: 3,
    whyThisMatters:
      "Social choices at this age preview the relational skills they'll carry into adolescence.",
  },
  {
    questionId: "social-6-12-005",
    category: "social",
    ageBand: "6-12",
    themeLabel: "Between People...",
    prompt: "When conflicts happen between friends, what role do you usually end up playing?",
    depthRating: 3,
    whyThisMatters:
      "Social choices at this age preview the relational skills they'll carry into adolescence.",
  },
  {
    questionId: "social-6-12-006",
    category: "social",
    ageBand: "6-12",
    themeLabel: "Between People...",
    prompt: "Has there been a time you misjudged someone before getting to know them?",
    depthRating: 3,
    whyThisMatters:
      "Social choices at this age preview the relational skills they'll carry into adolescence.",
  },
  {
    questionId: "social-6-12-007",
    category: "social",
    ageBand: "6-12",
    themeLabel: "Between People...",
    prompt: "Is there a kind of person you find it easy to be around, even if you're not sure why?",
    depthRating: 3,
    whyThisMatters:
      "Social choices at this age preview the relational skills they'll carry into adolescence.",
  },
  {
    questionId: "social-6-12-008",
    category: "social",
    ageBand: "6-12",
    themeLabel: "Between People...",
    prompt:
      "When you think about trust, is there something that makes you trust someone more quickly — or less?",
    depthRating: 3,
    whyThisMatters:
      "Social choices at this age preview the relational skills they'll carry into adolescence.",
  },
  {
    questionId: "social-6-12-009",
    category: "social",
    ageBand: "6-12",
    themeLabel: "Between People...",
    prompt:
      "Has there been a moment where being kind to someone changed how you felt about yourself?",
    depthRating: 3,
    whyThisMatters:
      "Social choices at this age preview the relational skills they'll carry into adolescence.",
  },
  {
    questionId: "social-6-12-010",
    category: "social",
    ageBand: "6-12",
    themeLabel: "Between People...",
    prompt:
      "Is there a group dynamic — at school, with friends, on a team — that you've noticed and thought about?",
    depthRating: 3,
    whyThisMatters:
      "Social choices at this age preview the relational skills they'll carry into adolescence.",
  },
  {
    questionId: "social-6-12-011",
    category: "social",
    ageBand: "6-12",
    themeLabel: "Between People...",
    prompt: "When you disagree with a friend, what usually happens next?",
    depthRating: 3,
    whyThisMatters:
      "Social choices at this age preview the relational skills they'll carry into adolescence.",
  },
  {
    questionId: "social-6-12-012",
    category: "social",
    ageBand: "6-12",
    themeLabel: "Between People...",
    prompt: "Is there someone you look out for, even if they don't know it?",
    depthRating: 3,
    whyThisMatters:
      "Social choices at this age preview the relational skills they'll carry into adolescence.",
  },
  {
    questionId: "social-6-12-013",
    category: "social",
    ageBand: "6-12",
    themeLabel: "Between People...",
    prompt: "Has there been a time you felt like an outsider, even somewhere familiar?",
    depthRating: 3,
    whyThisMatters:
      "Social choices at this age preview the relational skills they'll carry into adolescence.",
  },
  {
    questionId: "identity-6-12-001",
    category: "identity",
    ageBand: "6-12",
    themeLabel: "Becoming You...",
    prompt: "Is there something about yourself that you've only recently figured out?",
    depthRating: 4,
    whyThisMatters:
      "Identity questions get quieter as children age — asking now keeps the door open.",
  },
  {
    questionId: "identity-6-12-002",
    category: "identity",
    ageBand: "6-12",
    themeLabel: "Becoming You...",
    prompt:
      "When you think about the things that make you 'you,' is there one that feels most important?",
    depthRating: 4,
    whyThisMatters:
      "Identity questions get quieter as children age — asking now keeps the door open.",
  },
  {
    questionId: "identity-6-12-003",
    category: "identity",
    ageBand: "6-12",
    themeLabel: "Becoming You...",
    prompt:
      "Has there been a time you did something that didn't feel like 'you' — and how did that feel?",
    depthRating: 4,
    whyThisMatters:
      "Identity questions get quieter as children age — asking now keeps the door open.",
  },
  {
    questionId: "identity-6-12-004",
    category: "identity",
    ageBand: "6-12",
    themeLabel: "Becoming You...",
    prompt:
      "Is there a role you tend to play — in your family, with friends, at school — that you didn't choose but kind of fell into?",
    depthRating: 4,
    whyThisMatters:
      "Identity questions get quieter as children age — asking now keeps the door open.",
  },
  {
    questionId: "identity-6-12-005",
    category: "identity",
    ageBand: "6-12",
    themeLabel: "Becoming You...",
    prompt:
      "When you imagine the kind of adult you might become, is there something you hope is true about them?",
    depthRating: 4,
    whyThisMatters:
      "Identity questions get quieter as children age — asking now keeps the door open.",
  },
  {
    questionId: "identity-6-12-006",
    category: "identity",
    ageBand: "6-12",
    themeLabel: "Becoming You...",
    prompt: "Is there a value or belief you have that's different from what you were taught?",
    depthRating: 4,
    whyThisMatters:
      "Identity questions get quieter as children age — asking now keeps the door open.",
  },
  {
    questionId: "identity-6-12-007",
    category: "identity",
    ageBand: "6-12",
    themeLabel: "Becoming You...",
    prompt: "Has there been a moment where you felt completely confident, even briefly?",
    depthRating: 4,
    whyThisMatters:
      "Identity questions get quieter as children age — asking now keeps the door open.",
  },
  {
    questionId: "identity-6-12-008",
    category: "identity",
    ageBand: "6-12",
    themeLabel: "Becoming You...",
    prompt:
      "Is there something about how you think that feels different from how others seem to think?",
    depthRating: 4,
    whyThisMatters:
      "Identity questions get quieter as children age — asking now keeps the door open.",
  },
  {
    questionId: "identity-6-12-009",
    category: "identity",
    ageBand: "6-12",
    themeLabel: "Becoming You...",
    prompt:
      "When you make decisions, do you usually go with your gut, think it through, or ask others first?",
    depthRating: 4,
    whyThisMatters:
      "Identity questions get quieter as children age — asking now keeps the door open.",
  },
  {
    questionId: "identity-6-12-010",
    category: "identity",
    ageBand: "6-12",
    themeLabel: "Becoming You...",
    prompt: "Is there a part of your personality that's gotten stronger as you've grown?",
    depthRating: 4,
    whyThisMatters:
      "Identity questions get quieter as children age — asking now keeps the door open.",
  },
  {
    questionId: "identity-6-12-011",
    category: "identity",
    ageBand: "6-12",
    themeLabel: "Becoming You...",
    prompt: "Has there been a time you changed your mind about something important to you?",
    depthRating: 4,
    whyThisMatters:
      "Identity questions get quieter as children age — asking now keeps the door open.",
  },
  {
    questionId: "identity-6-12-012",
    category: "identity",
    ageBand: "6-12",
    themeLabel: "Becoming You...",
    prompt:
      "Is there something you do that, if you stopped doing it, would feel like losing a part of yourself?",
    depthRating: 4,
    whyThisMatters:
      "Identity questions get quieter as children age — asking now keeps the door open.",
  },
  {
    questionId: "identity-6-12-013",
    category: "identity",
    ageBand: "6-12",
    themeLabel: "Becoming You...",
    prompt:
      "When you think about your reputation — how people see you — is there a gap between that and how you see yourself?",
    depthRating: 4,
    whyThisMatters:
      "Identity questions get quieter as children age — asking now keeps the door open.",
  },
  {
    questionId: "imagination-6-12-001",
    category: "imagination",
    ageBand: "6-12",
    themeLabel: "What If...",
    prompt: "If you could give every person in the world one piece of advice, what would it be?",
    depthRating: 2,
    whyThisMatters:
      "Imagination at this age is still a safe place to explore values before real-world stakes rise.",
  },
  {
    questionId: "imagination-6-12-002",
    category: "imagination",
    ageBand: "6-12",
    themeLabel: "What If...",
    prompt: "Is there a story you've imagined that you've never written down or told anyone?",
    depthRating: 2,
    whyThisMatters:
      "Imagination at this age is still a safe place to explore values before real-world stakes rise.",
  },
  {
    questionId: "imagination-6-12-003",
    category: "imagination",
    ageBand: "6-12",
    themeLabel: "What If...",
    prompt:
      "If you could combine two things that don't normally go together — any two things — what would you create?",
    depthRating: 2,
    whyThisMatters:
      "Imagination at this age is still a safe place to explore values before real-world stakes rise.",
  },
  {
    questionId: "imagination-6-12-004",
    category: "imagination",
    ageBand: "6-12",
    themeLabel: "What If...",
    prompt:
      "What would a day look like if everyone had to tell the complete truth, no matter what?",
    depthRating: 2,
    whyThisMatters:
      "Imagination at this age is still a safe place to explore values before real-world stakes rise.",
  },
  {
    questionId: "imagination-6-12-005",
    category: "imagination",
    ageBand: "6-12",
    themeLabel: "What If...",
    prompt: "If you could design a holiday that didn't exist yet, what would it celebrate?",
    depthRating: 2,
    whyThisMatters:
      "Imagination at this age is still a safe place to explore values before real-world stakes rise.",
  },
  {
    questionId: "imagination-6-12-006",
    category: "imagination",
    ageBand: "6-12",
    themeLabel: "What If...",
    prompt:
      "Is there a 'what if' scenario you think about — like what if something in history had gone differently?",
    depthRating: 2,
    whyThisMatters:
      "Imagination at this age is still a safe place to explore values before real-world stakes rise.",
  },
  {
    questionId: "imagination-6-12-007",
    category: "imagination",
    ageBand: "6-12",
    themeLabel: "What If...",
    prompt:
      "If you could give an object a personality — like your backpack or your bike — what do you think it would be like?",
    depthRating: 2,
    whyThisMatters:
      "Imagination at this age is still a safe place to explore values before real-world stakes rise.",
  },
  {
    questionId: "imagination-6-12-008",
    category: "imagination",
    ageBand: "6-12",
    themeLabel: "What If...",
    prompt:
      "What would you do if you woke up one day and everyone forgot something specific — like how to read, or how to lie?",
    depthRating: 2,
    whyThisMatters:
      "Imagination at this age is still a safe place to explore values before real-world stakes rise.",
  },
  {
    questionId: "imagination-6-12-009",
    category: "imagination",
    ageBand: "6-12",
    themeLabel: "What If...",
    prompt:
      "If you could ask your future self for one piece of advice about right now, what do you think they'd say?",
    depthRating: 2,
    whyThisMatters:
      "Imagination at this age is still a safe place to explore values before real-world stakes rise.",
  },
  {
    questionId: "imagination-6-12-010",
    category: "imagination",
    ageBand: "6-12",
    themeLabel: "What If...",
    prompt:
      "Is there a place that exists in your imagination that feels as real to you as anywhere actual?",
    depthRating: 2,
    whyThisMatters:
      "Imagination at this age is still a safe place to explore values before real-world stakes rise.",
  },
];
