export const fieldJournalMedia = {
  cover: require("@/assets/journal/journal-landing.png"),
  /** Desk/candle/book scene with a blank parchment page (no creature art). */
  openBookScene: require("@/assets/journal/open_book_scene.png"),
  audio: {
    openBook: require("@/assets/audio/journal/open-book.mp3"),
    pageTurn: require("@/assets/audio/journal/page-turn.mp3"),
    candleAmbient: require("@/assets/audio/journal/candle-ambient.mp3"),
  },
  stillwater: {
    creatures0to2: require("@/assets/journal/stillwater/creatures_0-2.png"),
    /** Full-scene spreads (941×1672) — clipped to the page slot in the reader. */
    creatures3to5: require("@/assets/journal/stillwater/3-5_page.png"),
    creatures6to8: require("@/assets/journal/stillwater/6-8_page.png"),
    creatures9to11: require("@/assets/journal/stillwater/9-11_page.png"),
    creatures12to14: require("@/assets/journal/stillwater/12-14_page.png"),
    creatures15to17: require("@/assets/journal/stillwater/15-17_page.png"),
    creatures18to20: require("@/assets/journal/stillwater/18-20_page.png"),
    creatures21to23: require("@/assets/journal/stillwater/21-23_page.png"),
    creatures24to26: require("@/assets/journal/stillwater/24-26_page.png"),
    creatures27to29: require("@/assets/journal/stillwater/27-29_page.png"),
    creatures30to32: require("@/assets/journal/stillwater/30-33_page.png"),
    creatures33to35: require("@/assets/journal/stillwater/34-35_page.png"),
    creatures36to38: require("@/assets/journal/stillwater/36-38_page.png"),
    creatures39to41: require("@/assets/journal/stillwater/39-41_page.png"),
    creatures42to43: require("@/assets/journal/stillwater/42-43_page.png"),
    creatures44to46: require("@/assets/journal/stillwater/creatures_44-46.png"),
    creatures47to49: require("@/assets/journal/stillwater/creatures_47-49.png"),
    creatures50to52: require("@/assets/journal/stillwater/creatures_50-52.png"),
    creatures53to55: require("@/assets/journal/stillwater/creatures_53-55.png"),
    creatures56to57: require("@/assets/journal/stillwater/creatures_56-57.png"),
    creatures58to60: require("@/assets/journal/stillwater/creatures_58-60.png"),
    creatures61to63: require("@/assets/journal/stillwater/creatures_61-63.png"),
    creatures64to66: require("@/assets/journal/stillwater/creatures_64-66.png"),
    creatures67to69: require("@/assets/journal/stillwater/67-69_page.png"),
    creatures70to71: require("@/assets/journal/stillwater/70-71_page.png"),
    creatures72to74: require("@/assets/journal/stillwater/72-74_page.png"),
  },
} as const;
