// Auto-generated from creatures150.ts — do not edit by hand.
import type { CreatureRef } from "./encounterEngine";

export const CREATURE_REFS: CreatureRef[] = [
  {
    creatureTypeId: "puddle-dart",
    displayName: "Puddle Dart",
    poolTier: "common",
    elementType: "fire",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "bubble-mote",
    displayName: "Bubble Mote",
    poolTier: "common",
    elementType: "water",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "moss-skipper",
    displayName: "Moss Skipper",
    poolTier: "common",
    elementType: "wind",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "spark-pebble",
    displayName: "Spark Pebble",
    poolTier: "common",
    elementType: "electric",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "reed-tail",
    displayName: "Reed Tail",
    poolTier: "common",
    elementType: "fire",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "cloud-fin",
    displayName: "Cloud Fin",
    poolTier: "common",
    elementType: "water",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "hinge-glider",
    displayName: "Hinge Glider",
    poolTier: "common",
    elementType: "wind",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "amber-ring",
    displayName: "Amber Ring",
    poolTier: "common",
    elementType: "electric",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "shore-ghost",
    displayName: "Shore Ghost",
    poolTier: "common",
    elementType: "fire",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "knot-swimmer",
    displayName: "Knot Swimmer",
    poolTier: "common",
    elementType: "water",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "petal-dart",
    displayName: "Petal Dart",
    poolTier: "common",
    elementType: "wind",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "chalk-line",
    displayName: "Chalk Line",
    poolTier: "common",
    elementType: "electric",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "tide-pup",
    displayName: "Tide Pup",
    poolTier: "common",
    elementType: "fire",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "mirror-leaf",
    displayName: "Mirror Leaf",
    poolTier: "common",
    elementType: "water",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "blink-swimmer",
    displayName: "Blink Swimmer",
    poolTier: "common",
    elementType: "wind",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "gilt-minnow",
    displayName: "Gilt Minnow",
    poolTier: "common",
    elementType: "electric",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "rust-belly",
    displayName: "Rust Belly",
    poolTier: "common",
    elementType: "fire",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "soft-arch",
    displayName: "Soft Arch",
    poolTier: "common",
    elementType: "water",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "hollow-bell",
    displayName: "Hollow Bell",
    poolTier: "common",
    elementType: "wind",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "coil-spark",
    displayName: "Coil Spark",
    poolTier: "common",
    elementType: "electric",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "fog-glider",
    displayName: "Fog Glider",
    poolTier: "common",
    elementType: "fire",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "pool-penny",
    displayName: "Pool Penny",
    poolTier: "common",
    elementType: "water",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "wick-fin",
    displayName: "Wick Fin",
    poolTier: "common",
    elementType: "wind",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "loop-drifter",
    displayName: "Loop Drifter",
    poolTier: "common",
    elementType: "electric",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "bone-float",
    displayName: "Bone Float",
    poolTier: "common",
    elementType: "fire",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "green-bead",
    displayName: "Green Bead",
    poolTier: "common",
    elementType: "water",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "pine-needle",
    displayName: "Pine Needle",
    poolTier: "common",
    elementType: "wind",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "faint-arc",
    displayName: "Faint Arc",
    poolTier: "common",
    elementType: "electric",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "river-coin",
    displayName: "River Coin",
    poolTier: "common",
    elementType: "fire",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "dusk-mote",
    displayName: "Dusk Mote",
    poolTier: "common",
    elementType: "water",
    rodRequired: "basic",
    peakWonderGate: 0,
  },
  {
    creatureTypeId: "ember-darter",
    displayName: "Ember Darter",
    poolTier: "rare",
    elementType: "fire",
    rodRequired: "rare1",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "cinder-veil",
    displayName: "Cinder Veil",
    poolTier: "rare",
    elementType: "fire",
    rodRequired: "rare1",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "flare-scout",
    displayName: "Flare Scout",
    poolTier: "rare",
    elementType: "fire",
    rodRequired: "rare1",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "hearthfin",
    displayName: "Hearthfin",
    poolTier: "rare",
    elementType: "fire",
    rodRequired: "rare1",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "scorchtail",
    displayName: "Scorchtail",
    poolTier: "rare",
    elementType: "fire",
    rodRequired: "rare1",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "soot-drifter",
    displayName: "Soot Drifter",
    poolTier: "rare",
    elementType: "fire",
    rodRequired: "rare1",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "forge-wraith",
    displayName: "Forge Wraith",
    poolTier: "rare",
    elementType: "fire",
    rodRequired: "rare1",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "cinderback",
    displayName: "Cinderback",
    poolTier: "rare",
    elementType: "fire",
    rodRequired: "rare1",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "heatwave-glide",
    displayName: "Heatwave Glide",
    poolTier: "rare",
    elementType: "fire",
    rodRequired: "rare1",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "tinder-swift",
    displayName: "Tinder Swift",
    poolTier: "rare",
    elementType: "fire",
    rodRequired: "rare1",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "ashwing",
    displayName: "Ashwing",
    poolTier: "rare",
    elementType: "fire",
    rodRequired: "rare1",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "solstice-runner",
    displayName: "Solstice Runner",
    poolTier: "rare",
    elementType: "fire",
    rodRequired: "rare1",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "blaze-tender",
    displayName: "Blaze Tender",
    poolTier: "rare",
    elementType: "fire",
    rodRequired: "rare1",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "coal-sentinel",
    displayName: "Coal Sentinel",
    poolTier: "rare",
    elementType: "fire",
    rodRequired: "rare1",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "tide-whisper",
    displayName: "Tide Whisper",
    poolTier: "rare",
    elementType: "water",
    rodRequired: "rare2",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "mirror-minnow",
    displayName: "Mirror Minnow",
    poolTier: "rare",
    elementType: "water",
    rodRequired: "rare2",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "current-guide",
    displayName: "Current Guide",
    poolTier: "rare",
    elementType: "water",
    rodRequired: "rare2",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "still-pool",
    displayName: "Still Pool",
    poolTier: "rare",
    elementType: "water",
    rodRequired: "rare2",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "flow-keeper",
    displayName: "Flow Keeper",
    poolTier: "rare",
    elementType: "water",
    rodRequired: "rare2",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "ripple-sage",
    displayName: "Ripple Sage",
    poolTier: "rare",
    elementType: "water",
    rodRequired: "rare2",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "deep-current",
    displayName: "Deep Current",
    poolTier: "rare",
    elementType: "water",
    rodRequired: "rare2",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "pool-weaver",
    displayName: "Pool Weaver",
    poolTier: "rare",
    elementType: "water",
    rodRequired: "rare2",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "heron-blue",
    displayName: "Heron Blue",
    poolTier: "rare",
    elementType: "water",
    rodRequired: "rare2",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "glassfin",
    displayName: "Glassfin",
    poolTier: "rare",
    elementType: "water",
    rodRequired: "rare2",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "spring-mouth",
    displayName: "Spring Mouth",
    poolTier: "rare",
    elementType: "water",
    rodRequired: "rare2",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "salt-runner",
    displayName: "Salt Runner",
    poolTier: "rare",
    elementType: "water",
    rodRequired: "rare2",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "winter-swimmer",
    displayName: "Winter Swimmer",
    poolTier: "rare",
    elementType: "water",
    rodRequired: "rare2",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "confluence",
    displayName: "Confluence",
    poolTier: "rare",
    elementType: "water",
    rodRequired: "rare2",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "breath-dart",
    displayName: "Breath Dart",
    poolTier: "rare",
    elementType: "wind",
    rodRequired: "rare3",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "whisperfin",
    displayName: "Whisperfin",
    poolTier: "rare",
    elementType: "wind",
    rodRequired: "rare3",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "drift-leaf",
    displayName: "Drift Leaf",
    poolTier: "rare",
    elementType: "wind",
    rodRequired: "rare3",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "gust-runner",
    displayName: "Gust Runner",
    poolTier: "rare",
    elementType: "wind",
    rodRequired: "rare3",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "language-lilt",
    displayName: "Language Lilt",
    poolTier: "rare",
    elementType: "wind",
    rodRequired: "rare3",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "zephyr-counsel",
    displayName: "Zephyr Counsel",
    poolTier: "rare",
    elementType: "wind",
    rodRequired: "rare3",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "echo-bird",
    displayName: "Echo Bird",
    poolTier: "rare",
    elementType: "wind",
    rodRequired: "rare3",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "paper-crane-fish",
    displayName: "Paper Crane Fish",
    poolTier: "rare",
    elementType: "wind",
    rodRequired: "rare3",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "wind-knot",
    displayName: "Wind Knot",
    poolTier: "rare",
    elementType: "wind",
    rodRequired: "rare3",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "canopy-drifter",
    displayName: "Canopy Drifter",
    poolTier: "rare",
    elementType: "wind",
    rodRequired: "rare3",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "feather-wake",
    displayName: "Feather Wake",
    poolTier: "rare",
    elementType: "wind",
    rodRequired: "rare3",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "voice-thread",
    displayName: "Voice Thread",
    poolTier: "rare",
    elementType: "wind",
    rodRequired: "rare3",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "gust-elder",
    displayName: "Gust Elder",
    poolTier: "rare",
    elementType: "wind",
    rodRequired: "rare3",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "stillpoint-wing",
    displayName: "Stillpoint Wing",
    poolTier: "rare",
    elementType: "wind",
    rodRequired: "rare3",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "spark-mote",
    displayName: "Spark Mote",
    poolTier: "rare",
    elementType: "electric",
    rodRequired: "rare4",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "signal-dart",
    displayName: "Signal Dart",
    poolTier: "rare",
    elementType: "electric",
    rodRequired: "rare4",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "arc-scout",
    displayName: "Arc Scout",
    poolTier: "rare",
    elementType: "electric",
    rodRequired: "rare4",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "volt-tender",
    displayName: "Volt Tender",
    poolTier: "rare",
    elementType: "electric",
    rodRequired: "rare4",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "resonance-fish",
    displayName: "Resonance Fish",
    poolTier: "rare",
    elementType: "electric",
    rodRequired: "rare4",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "charge-keeper",
    displayName: "Charge Keeper",
    poolTier: "rare",
    elementType: "electric",
    rodRequired: "rare4",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "field-weaver",
    displayName: "Field Weaver",
    poolTier: "rare",
    elementType: "electric",
    rodRequired: "rare4",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "ground-pulse",
    displayName: "Ground Pulse",
    poolTier: "rare",
    elementType: "electric",
    rodRequired: "rare4",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "arc-tender",
    displayName: "Arc Tender",
    poolTier: "rare",
    elementType: "electric",
    rodRequired: "rare4",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "static-keeper",
    displayName: "Static Keeper",
    poolTier: "rare",
    elementType: "electric",
    rodRequired: "rare4",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "fuse-swimmer",
    displayName: "Fuse Swimmer",
    poolTier: "rare",
    elementType: "electric",
    rodRequired: "rare4",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "bright-node",
    displayName: "Bright Node",
    poolTier: "rare",
    elementType: "electric",
    rodRequired: "rare4",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "current-arrow",
    displayName: "Current Arrow",
    poolTier: "rare",
    elementType: "electric",
    rodRequired: "rare4",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "zenith-mote",
    displayName: "Zenith Mote",
    poolTier: "rare",
    elementType: "electric",
    rodRequired: "rare4",
    peakWonderGate: 40,
  },
  {
    creatureTypeId: "prism-drifter",
    displayName: "Prism Drifter",
    poolTier: "rare",
    elementType: "any",
    rodRequired: "rare5",
    peakWonderGate: 65,
  },
  {
    creatureTypeId: "threshold-fish",
    displayName: "Threshold Fish",
    poolTier: "rare",
    elementType: "any",
    rodRequired: "rare5",
    peakWonderGate: 65,
  },
  {
    creatureTypeId: "double-current",
    displayName: "Double Current",
    poolTier: "rare",
    elementType: "any",
    rodRequired: "rare5",
    peakWonderGate: 65,
  },
  {
    creatureTypeId: "compass-glide",
    displayName: "Compass Glide",
    poolTier: "rare",
    elementType: "any",
    rodRequired: "rare5",
    peakWonderGate: 65,
  },
  {
    creatureTypeId: "convergence",
    displayName: "Convergence",
    poolTier: "rare",
    elementType: "any",
    rodRequired: "rare5",
    peakWonderGate: 65,
  },
  {
    creatureTypeId: "deep-mirror",
    displayName: "Deep Mirror",
    poolTier: "rare",
    elementType: "any",
    rodRequired: "rare5",
    peakWonderGate: 65,
  },
  {
    creatureTypeId: "phase-swimmer",
    displayName: "Phase Swimmer",
    poolTier: "rare",
    elementType: "any",
    rodRequired: "rare5",
    peakWonderGate: 65,
  },
  {
    creatureTypeId: "echo-twin",
    displayName: "Echo Twin",
    poolTier: "rare",
    elementType: "any",
    rodRequired: "rare5",
    peakWonderGate: 65,
  },
  {
    creatureTypeId: "origin-spark",
    displayName: "Origin Spark",
    poolTier: "rare",
    elementType: "any",
    rodRequired: "rare5",
    peakWonderGate: 65,
  },
  {
    creatureTypeId: "horizon-walker",
    displayName: "Horizon Walker",
    poolTier: "rare",
    elementType: "any",
    rodRequired: "rare5",
    peakWonderGate: 65,
  },
  {
    creatureTypeId: "memory-fish",
    displayName: "Memory Fish",
    poolTier: "rare",
    elementType: "any",
    rodRequired: "rare5",
    peakWonderGate: 65,
  },
  {
    creatureTypeId: "bridge-swimmer",
    displayName: "Bridge Swimmer",
    poolTier: "rare",
    elementType: "any",
    rodRequired: "rare5",
    peakWonderGate: 65,
  },
  {
    creatureTypeId: "liminal-glide",
    displayName: "Liminal Glide",
    poolTier: "rare",
    elementType: "any",
    rodRequired: "rare5",
    peakWonderGate: 65,
  },
  {
    creatureTypeId: "whole-current",
    displayName: "Whole Current",
    poolTier: "rare",
    elementType: "any",
    rodRequired: "rare5",
    peakWonderGate: 65,
  },
  {
    creatureTypeId: "magma-elder",
    displayName: "Magma Elder",
    poolTier: "epic",
    elementType: "fire",
    rodRequired: "epic1",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "pyrefish",
    displayName: "Pyrefish",
    poolTier: "epic",
    elementType: "fire",
    rodRequired: "epic1",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "solarfin-sovereign",
    displayName: "Solarfin Sovereign",
    poolTier: "epic",
    elementType: "fire",
    rodRequired: "epic1",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "crucible-fish",
    displayName: "Crucible Fish",
    poolTier: "epic",
    elementType: "fire",
    rodRequired: "epic1",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "phoenix-ray",
    displayName: "Phoenix Ray",
    poolTier: "epic",
    elementType: "fire",
    rodRequired: "epic1",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "deep-ember",
    displayName: "Deep Ember",
    poolTier: "epic",
    elementType: "fire",
    rodRequired: "epic1",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "furnace-elder",
    displayName: "Furnace Elder",
    poolTier: "epic",
    elementType: "fire",
    rodRequired: "epic1",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "corona-wraith",
    displayName: "Corona Wraith",
    poolTier: "epic",
    elementType: "fire",
    rodRequired: "epic1",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "inferno-calm",
    displayName: "Inferno Calm",
    poolTier: "epic",
    elementType: "fire",
    rodRequired: "epic1",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "forge-sovereign",
    displayName: "Forge Sovereign",
    poolTier: "epic",
    elementType: "fire",
    rodRequired: "epic1",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "stellar-drifter",
    displayName: "Stellar Drifter",
    poolTier: "epic",
    elementType: "fire",
    rodRequired: "epic1",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "radiance-keeper",
    displayName: "Radiance Keeper",
    poolTier: "epic",
    elementType: "fire",
    rodRequired: "epic1",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "prime-flame",
    displayName: "Prime Flame",
    poolTier: "epic",
    elementType: "fire",
    rodRequired: "epic1",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "abyssal-calm",
    displayName: "Abyssal Calm",
    poolTier: "epic",
    elementType: "water",
    rodRequired: "epic2",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "tidal-elder",
    displayName: "Tidal Elder",
    poolTier: "epic",
    elementType: "water",
    rodRequired: "epic2",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "origin-leviathan",
    displayName: "Origin Leviathan",
    poolTier: "epic",
    elementType: "water",
    rodRequired: "epic2",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "deep-tide",
    displayName: "Deep Tide",
    poolTier: "epic",
    elementType: "water",
    rodRequired: "epic2",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "ancient-mirror",
    displayName: "Ancient Mirror",
    poolTier: "epic",
    elementType: "water",
    rodRequired: "epic2",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "source-swimmer",
    displayName: "Source Swimmer",
    poolTier: "epic",
    elementType: "water",
    rodRequired: "epic2",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "bedrock-blue",
    displayName: "Bedrock Blue",
    poolTier: "epic",
    elementType: "water",
    rodRequired: "epic2",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "estuary-sage",
    displayName: "Estuary Sage",
    poolTier: "epic",
    elementType: "water",
    rodRequired: "epic2",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "pressure-drifter",
    displayName: "Pressure Drifter",
    poolTier: "epic",
    elementType: "water",
    rodRequired: "epic2",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "void-swimmer",
    displayName: "Void Swimmer",
    poolTier: "epic",
    elementType: "water",
    rodRequired: "epic2",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "undertow-sage",
    displayName: "Undertow Sage",
    poolTier: "epic",
    elementType: "water",
    rodRequired: "epic2",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "stillwater-elder",
    displayName: "Stillwater Elder",
    poolTier: "epic",
    elementType: "water",
    rodRequired: "epic2",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "first-tide",
    displayName: "First Tide",
    poolTier: "epic",
    elementType: "water",
    rodRequired: "epic2",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "gale-witness",
    displayName: "Gale Witness",
    poolTier: "epic",
    elementType: "wind",
    rodRequired: "epic3",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "storm-anchor",
    displayName: "Storm Anchor",
    poolTier: "epic",
    elementType: "wind",
    rodRequired: "epic3",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "sky-sovereign",
    displayName: "Sky Sovereign",
    poolTier: "epic",
    elementType: "wind",
    rodRequired: "epic3",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "elder-breath",
    displayName: "Elder Breath",
    poolTier: "epic",
    elementType: "wind",
    rodRequired: "epic3",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "word-root",
    displayName: "Word Root",
    poolTier: "epic",
    elementType: "wind",
    rodRequired: "epic3",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "voice-elder",
    displayName: "Voice Elder",
    poolTier: "epic",
    elementType: "wind",
    rodRequired: "epic3",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "fracture-calm",
    displayName: "Fracture Calm",
    poolTier: "epic",
    elementType: "wind",
    rodRequired: "epic3",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "resonance-elder",
    displayName: "Resonance Elder",
    poolTier: "epic",
    elementType: "wind",
    rodRequired: "epic3",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "canopy-sovereign",
    displayName: "Canopy Sovereign",
    poolTier: "epic",
    elementType: "wind",
    rodRequired: "epic3",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "breath-sovereign",
    displayName: "Breath Sovereign",
    poolTier: "epic",
    elementType: "wind",
    rodRequired: "epic3",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "gust-sovereign",
    displayName: "Gust Sovereign",
    poolTier: "epic",
    elementType: "wind",
    rodRequired: "epic3",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "deepwind-elder",
    displayName: "Deepwind Elder",
    poolTier: "epic",
    elementType: "wind",
    rodRequired: "epic3",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "lightning-elder",
    displayName: "Lightning Elder",
    poolTier: "epic",
    elementType: "electric",
    rodRequired: "epic4",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "aurora-wraith",
    displayName: "Aurora Wraith",
    poolTier: "epic",
    elementType: "electric",
    rodRequired: "epic4",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "zenith-sovereign",
    displayName: "Zenith Sovereign",
    poolTier: "epic",
    elementType: "electric",
    rodRequired: "epic4",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "network-elder",
    displayName: "Network Elder",
    poolTier: "epic",
    elementType: "electric",
    rodRequired: "epic4",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "deep-circuit",
    displayName: "Deep Circuit",
    poolTier: "epic",
    elementType: "electric",
    rodRequired: "epic4",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "quiet-charge",
    displayName: "Quiet Charge",
    poolTier: "epic",
    elementType: "electric",
    rodRequired: "epic4",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "grid-sovereign",
    displayName: "Grid Sovereign",
    poolTier: "epic",
    elementType: "electric",
    rodRequired: "epic4",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "field-sovereign",
    displayName: "Field Sovereign",
    poolTier: "epic",
    elementType: "electric",
    rodRequired: "epic4",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "arc-sovereign",
    displayName: "Arc Sovereign",
    poolTier: "epic",
    elementType: "electric",
    rodRequired: "epic4",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "coherence-fish",
    displayName: "Coherence Fish",
    poolTier: "epic",
    elementType: "electric",
    rodRequired: "epic4",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "resonant-sovereign",
    displayName: "Resonant Sovereign",
    poolTier: "epic",
    elementType: "electric",
    rodRequired: "epic4",
    peakWonderGate: 90,
  },
  {
    creatureTypeId: "deep-signal",
    displayName: "Deep Signal",
    poolTier: "epic",
    elementType: "electric",
    rodRequired: "epic4",
    peakWonderGate: 90,
  },
] as CreatureRef[];
