// AUTO-GENERATED by sync-economy-module.js — do not edit by hand.
import type { BaitTier, DiaryReflectionDepth, FishingClaimOutcome, PracticeKind } from "../types";

/** Authoritative reward fields returned by server callables — client displays only. */
export type AuthoritativeRewardFields = {
  wonderAwarded: number;
  materialsAwarded?: number;
  partsAwarded?: number;
};

export type PreviewOnlyFlag = {
  /** DEV preview — zero Firestore economy writes; show banner in UI. */
  previewOnly?: true;
};

export type FishingClaimClientSummary = AuthoritativeRewardFields & {
  outcome: FishingClaimOutcome;
  rarityIndicator: "common" | "uncommon" | "rare" | "epic";
  creatureTypeId?: string;
  creatureDisplayName?: string;
  spiritMessage?: string;
  /** Epoch ms when the claim was resolved — real field for journal margin date. */
  claimedAt: number;
  /**
   * Narrow miss routing for client SFX — no percentages.
   * Engine sets `reason: "wonder_gate" | "chance"` on misses.
   */
  metadata?: { reason?: string };
} & PreviewOnlyFlag;

export type CraftBaitResponse = {
  success: true;
  tier: BaitTier;
  baitKey: string;
  wonderSpent: number;
  materialsSpent: Partial<Record<"feather" | "scale" | "glimmerdust", number>>;
};

export type CompletePracticeResponse = {
  success: true;
  wonderAwarded: number;
  completionId: string;
};

export type SubmitDiaryEntryResponse = {
  success: true;
  wonderAwarded: number;
  depth: DiaryReflectionDepth;
  currentWonder: number;
  partsAwarded?: number;
  migrated?: boolean;
};

export type SubmitWellReflectionSuccess = AuthoritativeRewardFields & {
  success: true;
  newInsightCount: number;
  atlasEntryId: string;
} & PreviewOnlyFlag;
