// AUTO-GENERATED by sync-economy-module.js — do not edit by hand.
/** Firestore tx read cap — leave headroom for user + idempotency reads. */
export const MAX_LEDGER_READS_PER_TX = 450;

/** Proactive compaction when total ledger rows exceed this count. */
export const COMPACT_WHEN_TOTAL_ENTRIES = 350;

/** Ledger rows left unread after compaction (tail query). */
export const COMPACT_KEEP_TAIL_ENTRIES = 100;

/** Refuse commit when tail alone exceeds this (force compaction). */
export const COMPACT_TAIL_HARD_LIMIT = 300;

/** Log/metric hint when tail exceeds this size. */
export const COMPACT_TAIL_LOG_THRESHOLD = 200;
