// AUTO-GENERATED by sync-economy-module.js — do not edit by hand.
import assert from "node:assert/strict";
import test from "node:test";

import { baitKeyFromCraftMetadata, foldBaitInventoryFromLedger } from "./foldBaitInventory";
import type { EconomyLedgerEntry } from "./types";

function entry(overrides: Partial<EconomyLedgerEntry>): EconomyLedgerEntry {
  return {
    id: "ledger_1",
    uid: "user_a",
    timestamp: Date.now(),
    actionType: "bait_craft",
    source: "bait_craft",
    deltaCurrentWonder: 0,
    deltaStoredWonder: 0,
    deltaParts: 0,
    deltaMaterials: {},
    idempotencyKey: "bait:1",
    metadata: {},
    schemaVersion: 1,
    ...overrides,
  };
}

test("baitKeyFromCraftMetadata prefers baitKey over tier", () => {
  assert.equal(baitKeyFromCraftMetadata({ baitKey: "scale_bait", tier: "basic" }), "scale_bait");
});

test("baitKeyFromCraftMetadata maps tier when baitKey absent", () => {
  assert.equal(baitKeyFromCraftMetadata({ tier: "rare" }), "scale_bait");
});

test("foldBaitInventoryFromLedger crafts and deducts consumable baits", () => {
  const folded = foldBaitInventoryFromLedger([
    entry({ metadata: { baitKey: "feather_bait" } }),
    entry({
      id: "ledger_2",
      actionType: "cast_create",
      source: "fishing_catch",
      metadata: { baitUsed: "feather_bait", baitDeducted: true },
    }),
    entry({
      id: "ledger_3",
      metadata: { tier: "rare" },
    }),
  ]);

  assert.deepEqual(folded, {
    feather_bait: 0,
    scale_bait: 1,
    glimmerdust_bait: 0,
    random_bait: 0,
  });
});

test("foldBaitInventoryFromLedger ignores random_bait cast_create", () => {
  const folded = foldBaitInventoryFromLedger([
    entry({
      id: "ledger_cast",
      actionType: "cast_create",
      source: "fishing_catch",
      metadata: { baitUsed: "random_bait", baitDeducted: false },
    }),
  ]);

  assert.deepEqual(folded, {
    feather_bait: 0,
    scale_bait: 0,
    glimmerdust_bait: 0,
    random_bait: 0,
  });
});
