// AUTO-GENERATED by sync-economy-module.js — do not edit by hand.
import type { EntityId, WonderSource } from "../types";

export type EconomyActionType =
  | "well_reflection"
  | "fishing_claim"
  | "lesson_complete"
  | "craft_start"
  | "craft_collect"
  | "bait_craft"
  | "practice_complete"
  | "diary_reflection"
  | "compensation"
  | "cast_create"
  | "cast_cancel"
  | "rod_equip"
  | "well_assign"
  | "well_reroll"
  | "purchase_verify"
  | "fishing_reset";

export type EconomyErrorCode =
  | "INSUFFICIENT_WONDER"
  | "NEGATIVE_BALANCE_GUARD"
  | "IDEMPOTENCY_CONFLICT"
  | "INVALID_AMOUNT"
  | "LEDGER_READ_LIMIT";

export class EconomyError extends Error {
  constructor(
    readonly code: EconomyErrorCode,
    message: string,
    readonly details?: Record<string, unknown>,
  ) {
    super(message);
    this.name = "EconomyError";
  }
}

export type EconomyLedgerEntry = {
  id: EntityId;
  uid: EntityId;
  timestamp: number;
  actionType: EconomyActionType;
  source: WonderSource;
  deltaCurrentWonder: number;
  deltaStoredWonder: number;
  deltaParts: number;
  deltaMaterials: Partial<Record<"feather" | "scale" | "glimmerdust", number>>;
  idempotencyKey: string;
  correlationId?: string;
  metadata: Record<string, unknown>;
  schemaVersion: 1;
};

export type EconomyIdempotencyRecord<T = unknown> = {
  idempotencyKey: string;
  ledgerEntryId: string;
  committedAt: number;
  response: T;
};

export type EconomyCommitResult<T> = {
  committed: boolean;
  result: T;
  ledgerEntryId: string;
};

/** Folded prefix snapshot — users/{uid}/economyLedgerCheckpoint/summary (server-write only). */
export type EconomyLedgerCheckpoint = {
  schemaVersion: 1;
  foldedThroughTimestamp: number;
  foldedThroughEntryId: string;
  foldedEntryCount: number;
  foldSums: {
    currentWonder: number;
    storedWonder: number;
    parts: number;
    feather: number;
    scale: number;
    glimmerdust: number;
  };
  lifetimeWonderEarned: number;
  compactedAt: number;
  compactedBy: "scheduled" | "admin" | "inline";
};

export const ECONOMY_LEDGER_CHECKPOINT_DOC_ID = "summary";

/** Optional typed fields on EconomyLedgerEntry.metadata */
export type EconomyLedgerMetadata = {
  wonderTransactionId?: string;
  correctsEntryId?: string;
  compensationReason?: string;
  migratedFromWonderTransactionId?: string;
  claimId?: string;
  outcome?: "catch" | "miss" | "duplicate";
  creatureTypeId?: string;
  duplicate?: boolean;
  [key: string]: unknown;
};
