"use strict";
// AUTO-GENERATED by sync-well-module.js — do not edit by hand.
/** Merged Well question catalog indices. */
Object.defineProperty(exports, "__esModule", { value: true });
exports.QUESTIONS_BY_CATEGORY =
  exports.QUESTIONS_BY_AGE_BAND =
  exports.WELL_QUESTION_BY_ID =
  exports.WELL_QUESTIONS =
  exports.WELL_QUESTIONS_6_12 =
  exports.WELL_QUESTIONS_4_6 =
    void 0;
exports.getWellQuestionById = getWellQuestionById;
exports.isValidWellQuestionId = isValidWellQuestionId;
const catalog_4_6_1 = require("./catalog-4-6");
const catalog_6_12_1 = require("./catalog-6-12");
var catalog_4_6_2 = require("./catalog-4-6");
Object.defineProperty(exports, "WELL_QUESTIONS_4_6", {
  enumerable: true,
  get: function () {
    return catalog_4_6_2.WELL_QUESTIONS_4_6;
  },
});
var catalog_6_12_2 = require("./catalog-6-12");
Object.defineProperty(exports, "WELL_QUESTIONS_6_12", {
  enumerable: true,
  get: function () {
    return catalog_6_12_2.WELL_QUESTIONS_6_12;
  },
});
exports.WELL_QUESTIONS = [
  ...catalog_4_6_1.WELL_QUESTIONS_4_6,
  ...catalog_6_12_1.WELL_QUESTIONS_6_12,
];
exports.WELL_QUESTION_BY_ID = Object.fromEntries(
  exports.WELL_QUESTIONS.map((question) => [question.questionId, question]),
);
exports.QUESTIONS_BY_AGE_BAND = {
  "4-6": catalog_4_6_1.WELL_QUESTIONS_4_6,
  "6-12": catalog_6_12_1.WELL_QUESTIONS_6_12,
};
exports.QUESTIONS_BY_CATEGORY = exports.WELL_QUESTIONS.reduce((acc, question) => {
  if (!acc[question.category]) acc[question.category] = [];
  acc[question.category].push(question);
  return acc;
}, {});
function getWellQuestionById(questionId) {
  return exports.WELL_QUESTION_BY_ID[questionId];
}
function isValidWellQuestionId(questionId, ageBand) {
  const question = exports.WELL_QUESTION_BY_ID[questionId];
  if (!question) return false;
  if (ageBand && question.ageBand !== ageBand) return false;
  return true;
}
