"use strict";
// AUTO-GENERATED by sync-well-module.js — do not edit by hand.
/** Auto-generated by scripts/generate_well_catalog.py — do not edit by hand. */
Object.defineProperty(exports, "__esModule", { value: true });
exports.WELL_QUESTIONS_4_6 = void 0;
exports.WELL_QUESTIONS_4_6 = [
  {
    questionId: "curiosity-4-6-001",
    category: "curiosity",
    ageBand: "4-6",
    themeLabel: "Wondering About...",
    prompt: "If you could ask the moon one question, what would you ask it?",
    depthRating: 2,
    whyThisMatters:
      "Young children reveal what fascinates them when questions feel playful, not like a quiz.",
  },
  {
    questionId: "curiosity-4-6-002",
    category: "curiosity",
    ageBand: "4-6",
    themeLabel: "Wondering About...",
    prompt: "What's something you see every day that you still don't know how it works?",
    depthRating: 2,
    whyThisMatters:
      "Young children reveal what fascinates them when questions feel playful, not like a quiz.",
  },
  {
    questionId: "curiosity-4-6-003",
    category: "curiosity",
    ageBand: "4-6",
    themeLabel: "Wondering About...",
    prompt: "If a bug could talk to you, what do you think it would want to tell you?",
    depthRating: 2,
    whyThisMatters:
      "Young children reveal what fascinates them when questions feel playful, not like a quiz.",
  },
  {
    questionId: "curiosity-4-6-004",
    category: "curiosity",
    ageBand: "4-6",
    themeLabel: "Wondering About...",
    prompt:
      "If you could shrink down and explore one ordinary object up close, what would you pick?",
    depthRating: 2,
    whyThisMatters:
      "Young children reveal what fascinates them when questions feel playful, not like a quiz.",
  },
  {
    questionId: "curiosity-4-6-005",
    category: "curiosity",
    ageBand: "4-6",
    themeLabel: "Wondering About...",
    prompt: "What's a question about animals that nobody's ever been able to answer for you?",
    depthRating: 2,
    whyThisMatters:
      "Young children reveal what fascinates them when questions feel playful, not like a quiz.",
  },
  {
    questionId: "curiosity-4-6-006",
    category: "curiosity",
    ageBand: "4-6",
    themeLabel: "Wondering About...",
    prompt:
      "If you could understand any language in the world for just one day, which would you choose and what would you want to hear?",
    depthRating: 2,
    whyThisMatters:
      "Young children reveal what fascinates them when questions feel playful, not like a quiz.",
  },
  {
    questionId: "curiosity-4-6-007",
    category: "curiosity",
    ageBand: "4-6",
    themeLabel: "Wondering About...",
    prompt:
      "Is there a place near our home you've always wondered what's actually inside or behind?",
    depthRating: 2,
    whyThisMatters:
      "Young children reveal what fascinates them when questions feel playful, not like a quiz.",
  },
  {
    questionId: "curiosity-4-6-008",
    category: "curiosity",
    ageBand: "4-6",
    themeLabel: "Wondering About...",
    prompt:
      "If scientists let kids vote on what to study next, what would you want them to figure out?",
    depthRating: 2,
    whyThisMatters:
      "Young children reveal what fascinates them when questions feel playful, not like a quiz.",
  },
  {
    questionId: "curiosity-4-6-009",
    category: "curiosity",
    ageBand: "4-6",
    themeLabel: "Wondering About...",
    prompt: "What's something you've seen that made you think 'wait, how does that even work?'",
    depthRating: 2,
    whyThisMatters:
      "Young children reveal what fascinates them when questions feel playful, not like a quiz.",
  },
  {
    questionId: "curiosity-4-6-010",
    category: "curiosity",
    ageBand: "4-6",
    themeLabel: "Wondering About...",
    prompt:
      "If you could follow one person around for a day just to see what they do, who would it be?",
    depthRating: 2,
    whyThisMatters:
      "Young children reveal what fascinates them when questions feel playful, not like a quiz.",
  },
  {
    questionId: "curiosity-4-6-011",
    category: "curiosity",
    ageBand: "4-6",
    themeLabel: "Wondering About...",
    prompt: "What's a question you've been saving up to ask someone older than you?",
    depthRating: 2,
    whyThisMatters:
      "Young children reveal what fascinates them when questions feel playful, not like a quiz.",
  },
  {
    questionId: "curiosity-4-6-012",
    category: "curiosity",
    ageBand: "4-6",
    themeLabel: "Wondering About...",
    prompt: "If you could take apart any machine just to see its insides, what would you choose?",
    depthRating: 2,
    whyThisMatters:
      "Young children reveal what fascinates them when questions feel playful, not like a quiz.",
  },
  {
    questionId: "curiosity-4-6-013",
    category: "curiosity",
    ageBand: "4-6",
    themeLabel: "Wondering About...",
    prompt:
      "Is there something in nature you've watched closely enough to notice something most people miss?",
    depthRating: 2,
    whyThisMatters:
      "Young children reveal what fascinates them when questions feel playful, not like a quiz.",
  },
  {
    questionId: "worries-4-6-001",
    category: "worries",
    ageBand: "4-6",
    themeLabel: "Carrying Quietly...",
    prompt: "Is there something that feels a little scary right before you fall asleep?",
    depthRating: 3,
    whyThisMatters:
      "Small worries named early are easier to carry together before they grow louder.",
  },
  {
    questionId: "worries-4-6-002",
    category: "worries",
    ageBand: "4-6",
    themeLabel: "Carrying Quietly...",
    prompt: "If you had a worry button, what's one thing you'd want to push away?",
    depthRating: 3,
    whyThisMatters:
      "Small worries named early are easier to carry together before they grow louder.",
  },
  {
    questionId: "worries-4-6-003",
    category: "worries",
    ageBand: "4-6",
    themeLabel: "Carrying Quietly...",
    prompt: "Was there something today that felt bigger than you expected?",
    depthRating: 3,
    whyThisMatters:
      "Small worries named early are easier to carry together before they grow louder.",
  },
  {
    questionId: "worries-4-6-004",
    category: "worries",
    ageBand: "4-6",
    themeLabel: "Carrying Quietly...",
    prompt:
      "Is there a sound or feeling that makes you feel uneasy, even if you can't explain why?",
    depthRating: 3,
    whyThisMatters:
      "Small worries named early are easier to carry together before they grow louder.",
  },
  {
    questionId: "worries-4-6-005",
    category: "worries",
    ageBand: "4-6",
    themeLabel: "Carrying Quietly...",
    prompt:
      "When you imagine something going wrong, what does that usually look like in your head?",
    depthRating: 3,
    whyThisMatters:
      "Small worries named early are easier to carry together before they grow louder.",
  },
  {
    questionId: "worries-4-6-006",
    category: "worries",
    ageBand: "4-6",
    themeLabel: "Carrying Quietly...",
    prompt:
      "Has there been a moment lately where you felt like you had to handle something on your own?",
    depthRating: 3,
    whyThisMatters:
      "Small worries named early are easier to carry together before they grow louder.",
  },
  {
    questionId: "worries-4-6-007",
    category: "worries",
    ageBand: "4-6",
    themeLabel: "Carrying Quietly...",
    prompt: "Is there a part of your day that feels harder than the rest, even if it's small?",
    depthRating: 3,
    whyThisMatters:
      "Small worries named early are easier to carry together before they grow louder.",
  },
  {
    questionId: "worries-4-6-008",
    category: "worries",
    ageBand: "4-6",
    themeLabel: "Carrying Quietly...",
    prompt:
      "If you could warn someone about something before it happens to them, what would it be?",
    depthRating: 3,
    whyThisMatters:
      "Small worries named early are easier to carry together before they grow louder.",
  },
  {
    questionId: "worries-4-6-009",
    category: "worries",
    ageBand: "4-6",
    themeLabel: "Carrying Quietly...",
    prompt:
      "Has anyone ever said something that stuck with you longer than you think they realized?",
    depthRating: 3,
    whyThisMatters:
      "Small worries named early are easier to carry together before they grow louder.",
  },
  {
    questionId: "worries-4-6-010",
    category: "worries",
    ageBand: "4-6",
    themeLabel: "Carrying Quietly...",
    prompt:
      "Is there something you've been waiting for someone to notice without having to say it out loud?",
    depthRating: 3,
    whyThisMatters:
      "Small worries named early are easier to carry together before they grow louder.",
  },
  {
    questionId: "worries-4-6-011",
    category: "worries",
    ageBand: "4-6",
    themeLabel: "Carrying Quietly...",
    prompt: "When you think about getting older, is there anything about it that feels uncertain?",
    depthRating: 3,
    whyThisMatters:
      "Small worries named early are easier to carry together before they grow louder.",
  },
  {
    questionId: "worries-4-6-012",
    category: "worries",
    ageBand: "4-6",
    themeLabel: "Carrying Quietly...",
    prompt: "Has there been a time you felt left out, even if just a little?",
    depthRating: 3,
    whyThisMatters:
      "Small worries named early are easier to carry together before they grow louder.",
  },
  {
    questionId: "worries-4-6-013",
    category: "worries",
    ageBand: "4-6",
    themeLabel: "Carrying Quietly...",
    prompt: "Is there a 'what if' thought that comes back to you sometimes?",
    depthRating: 3,
    whyThisMatters:
      "Small worries named early are easier to carry together before they grow louder.",
  },
  {
    questionId: "excitement-4-6-001",
    category: "excitement",
    ageBand: "4-6",
    themeLabel: "Bright Right Now...",
    prompt: "What's something far away that you keep thinking about, even though it's not today?",
    depthRating: 2,
    whyThisMatters: "What lights them up today often becomes the thread you follow for years.",
  },
  {
    questionId: "excitement-4-6-002",
    category: "excitement",
    ageBand: "4-6",
    themeLabel: "Bright Right Now...",
    prompt:
      "If you could practice one thing every day until you were amazing at it, what would you pick?",
    depthRating: 2,
    whyThisMatters: "What lights them up today often becomes the thread you follow for years.",
  },
  {
    questionId: "excitement-4-6-003",
    category: "excitement",
    ageBand: "4-6",
    themeLabel: "Bright Right Now...",
    prompt: "What's a tiny thing that happened today that made you feel really good inside?",
    depthRating: 2,
    whyThisMatters: "What lights them up today often becomes the thread you follow for years.",
  },
  {
    questionId: "excitement-4-6-004",
    category: "excitement",
    ageBand: "4-6",
    themeLabel: "Bright Right Now...",
    prompt: "What's something you'd want to do again and again if you could?",
    depthRating: 2,
    whyThisMatters: "What lights them up today often becomes the thread you follow for years.",
  },
  {
    questionId: "excitement-4-6-005",
    category: "excitement",
    ageBand: "4-6",
    themeLabel: "Bright Right Now...",
    prompt: "If you could plan the perfect afternoon from start to finish, what would be in it?",
    depthRating: 2,
    whyThisMatters: "What lights them up today often becomes the thread you follow for years.",
  },
  {
    questionId: "excitement-4-6-006",
    category: "excitement",
    ageBand: "4-6",
    themeLabel: "Bright Right Now...",
    prompt: "Is there a place you've never been but feel like you'd really love?",
    depthRating: 2,
    whyThisMatters: "What lights them up today often becomes the thread you follow for years.",
  },
  {
    questionId: "excitement-4-6-007",
    category: "excitement",
    ageBand: "4-6",
    themeLabel: "Bright Right Now...",
    prompt:
      "What's something you're getting better at that makes you feel proud, even if no one's said anything about it?",
    depthRating: 2,
    whyThisMatters: "What lights them up today often becomes the thread you follow for years.",
  },
  {
    questionId: "excitement-4-6-008",
    category: "excitement",
    ageBand: "4-6",
    themeLabel: "Bright Right Now...",
    prompt:
      "If you could spend a whole day with someone you admire, what would you want to do together?",
    depthRating: 2,
    whyThisMatters: "What lights them up today often becomes the thread you follow for years.",
  },
  {
    questionId: "excitement-4-6-009",
    category: "excitement",
    ageBand: "4-6",
    themeLabel: "Bright Right Now...",
    prompt: "Is there a sound, smell, or feeling that instantly makes you happy?",
    depthRating: 2,
    whyThisMatters: "What lights them up today often becomes the thread you follow for years.",
  },
  {
    questionId: "excitement-4-6-010",
    category: "excitement",
    ageBand: "4-6",
    themeLabel: "Bright Right Now...",
    prompt:
      "What's something you'd want to learn that feels just a little bit out of reach right now?",
    depthRating: 2,
    whyThisMatters: "What lights them up today often becomes the thread you follow for years.",
  },
  {
    questionId: "excitement-4-6-011",
    category: "excitement",
    ageBand: "4-6",
    themeLabel: "Bright Right Now...",
    prompt: "If you could throw a party for any reason, what would the reason be?",
    depthRating: 2,
    whyThisMatters: "What lights them up today often becomes the thread you follow for years.",
  },
  {
    questionId: "excitement-4-6-012",
    category: "excitement",
    ageBand: "4-6",
    themeLabel: "Bright Right Now...",
    prompt: "What's a moment from this year that you'd want to remember forever?",
    depthRating: 2,
    whyThisMatters: "What lights them up today often becomes the thread you follow for years.",
  },
  {
    questionId: "excitement-4-6-013",
    category: "excitement",
    ageBand: "4-6",
    themeLabel: "Bright Right Now...",
    prompt: "Is there something you do that makes time feel like it goes by really fast?",
    depthRating: 2,
    whyThisMatters: "What lights them up today often becomes the thread you follow for years.",
  },
  {
    questionId: "interests-4-6-001",
    category: "interests",
    ageBand: "4-6",
    themeLabel: "Drawn Toward...",
    prompt: "If you got to show someone how to do something, what would you teach them?",
    depthRating: 2,
    whyThisMatters:
      "Noticing what they gravitate toward helps you offer the right invitations, not more activities.",
  },
  {
    questionId: "interests-4-6-002",
    category: "interests",
    ageBand: "4-6",
    themeLabel: "Drawn Toward...",
    prompt: "Who do you like watching — like someone who does something cool or interesting?",
    depthRating: 2,
    whyThisMatters:
      "Noticing what they gravitate toward helps you offer the right invitations, not more activities.",
  },
  {
    questionId: "interests-4-6-003",
    category: "interests",
    ageBand: "4-6",
    themeLabel: "Drawn Toward...",
    prompt: "If you found a treasure box, what kind of things would you hope were inside?",
    depthRating: 2,
    whyThisMatters:
      "Noticing what they gravitate toward helps you offer the right invitations, not more activities.",
  },
  {
    questionId: "interests-4-6-004",
    category: "interests",
    ageBand: "4-6",
    themeLabel: "Drawn Toward...",
    prompt: "If you had to organize a collection of something, what would you want to collect?",
    depthRating: 2,
    whyThisMatters:
      "Noticing what they gravitate toward helps you offer the right invitations, not more activities.",
  },
  {
    questionId: "interests-4-6-005",
    category: "interests",
    ageBand: "4-6",
    themeLabel: "Drawn Toward...",
    prompt: "Is there a job or role you've seen someone do that looks really satisfying?",
    depthRating: 2,
    whyThisMatters:
      "Noticing what they gravitate toward helps you offer the right invitations, not more activities.",
  },
  {
    questionId: "interests-4-6-006",
    category: "interests",
    ageBand: "4-6",
    themeLabel: "Drawn Toward...",
    prompt:
      "What's something you'd want to build if you had all the materials and tools you needed?",
    depthRating: 2,
    whyThisMatters:
      "Noticing what they gravitate toward helps you offer the right invitations, not more activities.",
  },
  {
    questionId: "interests-4-6-007",
    category: "interests",
    ageBand: "4-6",
    themeLabel: "Drawn Toward...",
    prompt: "If you could design your own room from scratch, what's the first thing you'd add?",
    depthRating: 2,
    whyThisMatters:
      "Noticing what they gravitate toward helps you offer the right invitations, not more activities.",
  },
  {
    questionId: "interests-4-6-008",
    category: "interests",
    ageBand: "4-6",
    themeLabel: "Drawn Toward...",
    prompt: "Is there a topic you'd want to read an entire book about, even if it's a strange one?",
    depthRating: 2,
    whyThisMatters:
      "Noticing what they gravitate toward helps you offer the right invitations, not more activities.",
  },
  {
    questionId: "interests-4-6-009",
    category: "interests",
    ageBand: "4-6",
    themeLabel: "Drawn Toward...",
    prompt: "What's something you've noticed that other people don't seem to pay attention to?",
    depthRating: 2,
    whyThisMatters:
      "Noticing what they gravitate toward helps you offer the right invitations, not more activities.",
  },
  {
    questionId: "interests-4-6-010",
    category: "interests",
    ageBand: "4-6",
    themeLabel: "Drawn Toward...",
    prompt:
      "If you could be really skilled at fixing one type of thing, what would you want it to be?",
    depthRating: 2,
    whyThisMatters:
      "Noticing what they gravitate toward helps you offer the right invitations, not more activities.",
  },
  {
    questionId: "interests-4-6-011",
    category: "interests",
    ageBand: "4-6",
    themeLabel: "Drawn Toward...",
    prompt:
      "Is there a type of story — adventure, mystery, funny, sad — that you're drawn to more than others?",
    depthRating: 2,
    whyThisMatters:
      "Noticing what they gravitate toward helps you offer the right invitations, not more activities.",
  },
  {
    questionId: "interests-4-6-012",
    category: "interests",
    ageBand: "4-6",
    themeLabel: "Drawn Toward...",
    prompt: "What's something you'd want to practice if practicing it didn't feel like work?",
    depthRating: 2,
    whyThisMatters:
      "Noticing what they gravitate toward helps you offer the right invitations, not more activities.",
  },
  {
    questionId: "interests-4-6-013",
    category: "interests",
    ageBand: "4-6",
    themeLabel: "Drawn Toward...",
    prompt:
      "If you could visit any kind of workplace just to see what happens there, where would you go?",
    depthRating: 2,
    whyThisMatters:
      "Noticing what they gravitate toward helps you offer the right invitations, not more activities.",
  },
  {
    questionId: "emotional-4-6-001",
    category: "emotional",
    ageBand: "4-6",
    themeLabel: "Feeling Both Ways...",
    prompt: "When you feel a big feeling, where does it feel like it's hiding in your body?",
    depthRating: 3,
    whyThisMatters: "Naming feelings in the body builds the vocabulary they'll use for a lifetime.",
  },
  {
    questionId: "emotional-4-6-002",
    category: "emotional",
    ageBand: "4-6",
    themeLabel: "Feeling Both Ways...",
    prompt:
      "Have you ever felt two feelings at the same time, like happy and a little sad together?",
    depthRating: 3,
    whyThisMatters: "Naming feelings in the body builds the vocabulary they'll use for a lifetime.",
  },
  {
    questionId: "emotional-4-6-003",
    category: "emotional",
    ageBand: "4-6",
    themeLabel: "Feeling Both Ways...",
    prompt:
      "When something doesn't go the way you wanted, what's the first thing that pops into your head?",
    depthRating: 3,
    whyThisMatters: "Naming feelings in the body builds the vocabulary they'll use for a lifetime.",
  },
  {
    questionId: "emotional-4-6-004",
    category: "emotional",
    ageBand: "4-6",
    themeLabel: "Feeling Both Ways...",
    prompt: "Is there a feeling you've had that you didn't have a name for?",
    depthRating: 3,
    whyThisMatters: "Naming feelings in the body builds the vocabulary they'll use for a lifetime.",
  },
  {
    questionId: "emotional-4-6-005",
    category: "emotional",
    ageBand: "4-6",
    themeLabel: "Feeling Both Ways...",
    prompt:
      "When you're upset, do you want someone close by, or do you want space? How do you usually know which?",
    depthRating: 3,
    whyThisMatters: "Naming feelings in the body builds the vocabulary they'll use for a lifetime.",
  },
  {
    questionId: "emotional-4-6-006",
    category: "emotional",
    ageBand: "4-6",
    themeLabel: "Feeling Both Ways...",
    prompt:
      "Has there been a time your feelings changed really fast, like from one thing to a totally different thing?",
    depthRating: 3,
    whyThisMatters: "Naming feelings in the body builds the vocabulary they'll use for a lifetime.",
  },
  {
    questionId: "emotional-4-6-007",
    category: "emotional",
    ageBand: "4-6",
    themeLabel: "Feeling Both Ways...",
    prompt:
      "When you feel proud of yourself, what does that feel like compared to when someone else is proud of you?",
    depthRating: 3,
    whyThisMatters: "Naming feelings in the body builds the vocabulary they'll use for a lifetime.",
  },
  {
    questionId: "emotional-4-6-008",
    category: "emotional",
    ageBand: "4-6",
    themeLabel: "Feeling Both Ways...",
    prompt: "Is there something that used to bother you a lot but doesn't anymore? What changed?",
    depthRating: 3,
    whyThisMatters: "Naming feelings in the body builds the vocabulary they'll use for a lifetime.",
  },
  {
    questionId: "emotional-4-6-009",
    category: "emotional",
    ageBand: "4-6",
    themeLabel: "Feeling Both Ways...",
    prompt: "When you feel nervous, is there anything that helps, even a little?",
    depthRating: 3,
    whyThisMatters: "Naming feelings in the body builds the vocabulary they'll use for a lifetime.",
  },
  {
    questionId: "emotional-4-6-010",
    category: "emotional",
    ageBand: "4-6",
    themeLabel: "Feeling Both Ways...",
    prompt: "Have you ever felt like crying but didn't know exactly why?",
    depthRating: 3,
    whyThisMatters: "Naming feelings in the body builds the vocabulary they'll use for a lifetime.",
  },
  {
    questionId: "emotional-4-6-011",
    category: "emotional",
    ageBand: "4-6",
    themeLabel: "Feeling Both Ways...",
    prompt: "Is there a feeling that's hard to talk about because it's hard to explain?",
    depthRating: 3,
    whyThisMatters: "Naming feelings in the body builds the vocabulary they'll use for a lifetime.",
  },
  {
    questionId: "emotional-4-6-012",
    category: "emotional",
    ageBand: "4-6",
    themeLabel: "Feeling Both Ways...",
    prompt: "When something makes you really angry, what usually happens right after the anger?",
    depthRating: 3,
    whyThisMatters: "Naming feelings in the body builds the vocabulary they'll use for a lifetime.",
  },
  {
    questionId: "emotional-4-6-013",
    category: "emotional",
    ageBand: "4-6",
    themeLabel: "Feeling Both Ways...",
    prompt:
      "Have you ever felt relieved about something you hadn't told anyone you were worried about?",
    depthRating: 3,
    whyThisMatters: "Naming feelings in the body builds the vocabulary they'll use for a lifetime.",
  },
  {
    questionId: "social-4-6-001",
    category: "social",
    ageBand: "4-6",
    themeLabel: "Between People...",
    prompt: "When something feels not fair, do you tell someone or keep it inside?",
    depthRating: 2,
    whyThisMatters:
      "How they experience fairness and friendship at four tells you what they need at six.",
  },
  {
    questionId: "social-4-6-002",
    category: "social",
    ageBand: "4-6",
    themeLabel: "Between People...",
    prompt: "Is there someone you know who doesn't get to go first very often?",
    depthRating: 2,
    whyThisMatters:
      "How they experience fairness and friendship at four tells you what they need at six.",
  },
  {
    questionId: "social-4-6-003",
    category: "social",
    ageBand: "4-6",
    themeLabel: "Between People...",
    prompt: "What's something a friend did that made you feel like they really know you?",
    depthRating: 2,
    whyThisMatters:
      "How they experience fairness and friendship at four tells you what they need at six.",
  },
  {
    questionId: "social-4-6-004",
    category: "social",
    ageBand: "4-6",
    themeLabel: "Between People...",
    prompt:
      "Is there someone you used to be close with but aren't as much anymore? What do you think happened?",
    depthRating: 2,
    whyThisMatters:
      "How they experience fairness and friendship at four tells you what they need at six.",
  },
  {
    questionId: "social-4-6-005",
    category: "social",
    ageBand: "4-6",
    themeLabel: "Between People...",
    prompt:
      "When you're in a group, do you usually end up leading, following, or somewhere in between?",
    depthRating: 2,
    whyThisMatters:
      "How they experience fairness and friendship at four tells you what they need at six.",
  },
  {
    questionId: "social-4-6-006",
    category: "social",
    ageBand: "4-6",
    themeLabel: "Between People...",
    prompt: "Has there been a time you stuck up for someone, or wished you had?",
    depthRating: 2,
    whyThisMatters:
      "How they experience fairness and friendship at four tells you what they need at six.",
  },
  {
    questionId: "social-4-6-007",
    category: "social",
    ageBand: "4-6",
    themeLabel: "Between People...",
    prompt: "Is there someone whose opinion of you matters more than you'd expect?",
    depthRating: 2,
    whyThisMatters:
      "How they experience fairness and friendship at four tells you what they need at six.",
  },
  {
    questionId: "social-4-6-008",
    category: "social",
    ageBand: "4-6",
    themeLabel: "Between People...",
    prompt: "When two people you know don't get along, how do you usually feel about it?",
    depthRating: 2,
    whyThisMatters:
      "How they experience fairness and friendship at four tells you what they need at six.",
  },
  {
    questionId: "social-4-6-009",
    category: "social",
    ageBand: "4-6",
    themeLabel: "Between People...",
    prompt: "Have you ever changed your mind about someone after getting to know them better?",
    depthRating: 2,
    whyThisMatters:
      "How they experience fairness and friendship at four tells you what they need at six.",
  },
  {
    questionId: "social-4-6-010",
    category: "social",
    ageBand: "4-6",
    themeLabel: "Between People...",
    prompt: "Is there a way you wish people understood you better?",
    depthRating: 2,
    whyThisMatters:
      "How they experience fairness and friendship at four tells you what they need at six.",
  },
  {
    questionId: "social-4-6-011",
    category: "social",
    ageBand: "4-6",
    themeLabel: "Between People...",
    prompt:
      "When someone's having a hard time, what do you usually do — or wish you knew how to do?",
    depthRating: 2,
    whyThisMatters:
      "How they experience fairness and friendship at four tells you what they need at six.",
  },
  {
    questionId: "social-4-6-012",
    category: "social",
    ageBand: "4-6",
    themeLabel: "Between People...",
    prompt: "Is there a group or place where you feel like you can really be yourself?",
    depthRating: 2,
    whyThisMatters:
      "How they experience fairness and friendship at four tells you what they need at six.",
  },
  {
    questionId: "social-4-6-013",
    category: "social",
    ageBand: "4-6",
    themeLabel: "Between People...",
    prompt: "Has there been a moment where you felt proud of how someone treated you?",
    depthRating: 2,
    whyThisMatters:
      "How they experience fairness and friendship at four tells you what they need at six.",
  },
  {
    questionId: "identity-4-6-001",
    category: "identity",
    ageBand: "4-6",
    themeLabel: "Becoming You...",
    prompt: "Do you act a little different at school than you do at home? What's different?",
    depthRating: 3,
    whyThisMatters:
      "Early self-stories are forming — your observations help them feel seen, not labeled.",
  },
  {
    questionId: "identity-4-6-002",
    category: "identity",
    ageBand: "4-6",
    themeLabel: "Becoming You...",
    prompt:
      "If someone watched you play for five minutes, what do you think they'd notice about you?",
    depthRating: 3,
    whyThisMatters:
      "Early self-stories are forming — your observations help them feel seen, not labeled.",
  },
  {
    questionId: "identity-4-6-003",
    category: "identity",
    ageBand: "4-6",
    themeLabel: "Becoming You...",
    prompt: "Has there been a time you did something and surprised yourself?",
    depthRating: 3,
    whyThisMatters:
      "Early self-stories are forming — your observations help them feel seen, not labeled.",
  },
  {
    questionId: "identity-4-6-004",
    category: "identity",
    ageBand: "4-6",
    themeLabel: "Becoming You...",
    prompt:
      "If you had to describe yourself using something other than words — like a color, an animal, or a weather type — what would it be?",
    depthRating: 3,
    whyThisMatters:
      "Early self-stories are forming — your observations help them feel seen, not labeled.",
  },
  {
    questionId: "identity-4-6-005",
    category: "identity",
    ageBand: "4-6",
    themeLabel: "Becoming You...",
    prompt: "Is there something about yourself that's changed a lot over the past year?",
    depthRating: 3,
    whyThisMatters:
      "Early self-stories are forming — your observations help them feel seen, not labeled.",
  },
  {
    questionId: "identity-4-6-006",
    category: "identity",
    ageBand: "4-6",
    themeLabel: "Becoming You...",
    prompt: "When do you feel most like 'yourself'?",
    depthRating: 3,
    whyThisMatters:
      "Early self-stories are forming — your observations help them feel seen, not labeled.",
  },
  {
    questionId: "identity-4-6-007",
    category: "identity",
    ageBand: "4-6",
    themeLabel: "Becoming You...",
    prompt: "Is there a version of you that only certain people get to see?",
    depthRating: 3,
    whyThisMatters:
      "Early self-stories are forming — your observations help them feel seen, not labeled.",
  },
  {
    questionId: "identity-4-6-008",
    category: "identity",
    ageBand: "4-6",
    themeLabel: "Becoming You...",
    prompt:
      "If you could keep one thing about yourself exactly the same forever, what would it be?",
    depthRating: 3,
    whyThisMatters:
      "Early self-stories are forming — your observations help them feel seen, not labeled.",
  },
  {
    questionId: "identity-4-6-009",
    category: "identity",
    ageBand: "4-6",
    themeLabel: "Becoming You...",
    prompt: "Has there been a moment where you felt like you were becoming more grown up?",
    depthRating: 3,
    whyThisMatters:
      "Early self-stories are forming — your observations help them feel seen, not labeled.",
  },
  {
    questionId: "identity-4-6-010",
    category: "identity",
    ageBand: "4-6",
    themeLabel: "Becoming You...",
    prompt: "Is there something people think about you that isn't quite right?",
    depthRating: 3,
    whyThisMatters:
      "Early self-stories are forming — your observations help them feel seen, not labeled.",
  },
  {
    questionId: "identity-4-6-011",
    category: "identity",
    ageBand: "4-6",
    themeLabel: "Becoming You...",
    prompt:
      "When you think about who you might be when you're older, is there something you hope stays the same?",
    depthRating: 3,
    whyThisMatters:
      "Early self-stories are forming — your observations help them feel seen, not labeled.",
  },
  {
    questionId: "identity-4-6-012",
    category: "identity",
    ageBand: "4-6",
    themeLabel: "Becoming You...",
    prompt: "Is there a quality in someone else that you wish you had more of?",
    depthRating: 3,
    whyThisMatters:
      "Early self-stories are forming — your observations help them feel seen, not labeled.",
  },
  {
    questionId: "identity-4-6-013",
    category: "identity",
    ageBand: "4-6",
    themeLabel: "Becoming You...",
    prompt: "Has there been a time you stood up for something you believed, even if it was small?",
    depthRating: 3,
    whyThisMatters:
      "Early self-stories are forming — your observations help them feel seen, not labeled.",
  },
  {
    questionId: "imagination-4-6-001",
    category: "imagination",
    ageBand: "4-6",
    themeLabel: "What If...",
    prompt: "If you could make one new rule for our house, what would it be?",
    depthRating: 2,
    whyThisMatters:
      "Imaginative play is how young children rehearse values, rules, and who they might become.",
  },
  {
    questionId: "imagination-4-6-002",
    category: "imagination",
    ageBand: "4-6",
    themeLabel: "What If...",
    prompt:
      "Do you ever pretend you're somewhere else while you're doing something boring, like brushing your teeth?",
    depthRating: 2,
    whyThisMatters:
      "Imaginative play is how young children rehearse values, rules, and who they might become.",
  },
  {
    questionId: "imagination-4-6-003",
    category: "imagination",
    ageBand: "4-6",
    themeLabel: "What If...",
    prompt: "If you woke up tomorrow with a new superpower, what would you want it to help you do?",
    depthRating: 2,
    whyThisMatters:
      "Imaginative play is how young children rehearse values, rules, and who they might become.",
  },
  {
    questionId: "imagination-4-6-004",
    category: "imagination",
    ageBand: "4-6",
    themeLabel: "What If...",
    prompt: "If your thoughts had a shape or color, what do you think they'd look like?",
    depthRating: 2,
    whyThisMatters:
      "Imaginative play is how young children rehearse values, rules, and who they might become.",
  },
  {
    questionId: "imagination-4-6-005",
    category: "imagination",
    ageBand: "4-6",
    themeLabel: "What If...",
    prompt:
      "If you could turn any everyday object into something magical, what would you choose and what would it do?",
    depthRating: 2,
    whyThisMatters:
      "Imaginative play is how young children rehearse values, rules, and who they might become.",
  },
  {
    questionId: "imagination-4-6-006",
    category: "imagination",
    ageBand: "4-6",
    themeLabel: "What If...",
    prompt: "Is there a place that exists only in your imagination that you go to sometimes?",
    depthRating: 2,
    whyThisMatters:
      "Imaginative play is how young children rehearse values, rules, and who they might become.",
  },
  {
    questionId: "imagination-4-6-007",
    category: "imagination",
    ageBand: "4-6",
    themeLabel: "What If...",
    prompt:
      "If animals could read minds, which animal do you think would be best at it, and what would they notice about people?",
    depthRating: 2,
    whyThisMatters:
      "Imaginative play is how young children rehearse values, rules, and who they might become.",
  },
  {
    questionId: "imagination-4-6-008",
    category: "imagination",
    ageBand: "4-6",
    themeLabel: "What If...",
    prompt: "If you could make a rule that every adult had to follow, what would it be?",
    depthRating: 2,
    whyThisMatters:
      "Imaginative play is how young children rehearse values, rules, and who they might become.",
  },
  {
    questionId: "imagination-4-6-009",
    category: "imagination",
    ageBand: "4-6",
    themeLabel: "What If...",
    prompt:
      "Is there a character — from a book, show, or your own imagination — who feels like they understand you?",
    depthRating: 2,
    whyThisMatters:
      "Imaginative play is how young children rehearse values, rules, and who they might become.",
  },
  {
    questionId: "imagination-4-6-010",
    category: "imagination",
    ageBand: "4-6",
    themeLabel: "What If...",
    prompt:
      "If the world went completely silent for one hour, what do you think you'd do with that hour?",
    depthRating: 2,
    whyThisMatters:
      "Imaginative play is how young children rehearse values, rules, and who they might become.",
  },
  {
    questionId: "imagination-4-6-011",
    category: "imagination",
    ageBand: "4-6",
    themeLabel: "What If...",
    prompt: "If you could give one ordinary day a soundtrack, what would it sound like?",
    depthRating: 2,
    whyThisMatters:
      "Imaginative play is how young children rehearse values, rules, and who they might become.",
  },
  {
    questionId: "imagination-4-6-012",
    category: "imagination",
    ageBand: "4-6",
    themeLabel: "What If...",
    prompt: "Is there a dream you've had that felt so real you weren't sure it wasn't?",
    depthRating: 2,
    whyThisMatters:
      "Imaginative play is how young children rehearse values, rules, and who they might become.",
  },
  {
    questionId: "imagination-4-6-013",
    category: "imagination",
    ageBand: "4-6",
    themeLabel: "What If...",
    prompt:
      "If you could send a message to yourself five years from now, what's one thing you'd want to say?",
    depthRating: 2,
    whyThisMatters:
      "Imaginative play is how young children rehearse values, rules, and who they might become.",
  },
];
