"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.hasAnsweredToday = hasAnsweredToday;
exports.mergeWellState = mergeWellState;
exports.getTodaysQuestion = getTodaysQuestion;
exports.canReroll = canReroll;
exports.applyReroll = applyReroll;
// AUTO-GENERATED by sync-well-module.js — do not edit by hand.
const random_1 = require("../random");
const catalog_1 = require("./catalog");
const types_1 = require("./types");
function hasAnsweredToday(state, today, questionId) {
  return state.currentQuestionDate === today && state.answeredQuestionIds.includes(questionId);
}
function mergeWellState(base) {
  return { ...types_1.DEFAULT_USER_WELL_STATE, ...base };
}
/** Sticky daily question — returns existing if same day and still valid in catalog. */
function getTodaysQuestion(state, ageBand, today, seed) {
  if (
    state.currentQuestionDate === today &&
    state.currentQuestionId &&
    catalog_1.WELL_QUESTION_BY_ID[state.currentQuestionId]?.ageBand === ageBand
  ) {
    const existing = catalog_1.WELL_QUESTION_BY_ID[state.currentQuestionId];
    if (existing) return { question: existing, statePatch: null };
  }
  const { question, questionId } = selectNewQuestion(state, ageBand, seed);
  return {
    question,
    statePatch: {
      currentQuestionId: questionId,
      currentQuestionDate: today,
      rerollsUsedToday: 0,
      askedQuestionIds: [...state.askedQuestionIds, questionId],
    },
  };
}
function selectNewQuestion(state, ageBand, seed) {
  const pool = catalog_1.QUESTIONS_BY_AGE_BAND[ageBand];
  const asked = new Set(state.askedQuestionIds);
  const unseen = pool.filter((question) => !asked.has(question.questionId));
  let candidates;
  if (unseen.length > 0) {
    candidates = unseen;
  } else {
    const recentIds = new Set(state.askedQuestionIds.slice(-types_1.RECENT_REPEAT_AVOIDANCE));
    const notRecent = pool.filter((question) => !recentIds.has(question.questionId));
    candidates = notRecent.length > 0 ? notRecent : pool;
  }
  const rotated = rotateByCategory(candidates, state);
  const index = (0, random_1.pickIndex)(seed, rotated.length);
  const question = rotated[index];
  return { question, questionId: question.questionId };
}
function rotateByCategory(candidates, state) {
  const recentCategories = new Set(
    state.askedQuestionIds
      .slice(-types_1.RECENT_CATEGORY_WINDOW)
      .map((id) => catalog_1.WELL_QUESTION_BY_ID[id]?.category)
      .filter(Boolean),
  );
  const preferred = candidates.filter((question) => !recentCategories.has(question.category));
  return preferred.length > 0 ? preferred : candidates;
}
function canReroll(state, today) {
  return (
    state.currentQuestionDate === today && state.rerollsUsedToday < types_1.MAX_REROLLS_PER_DAY
  );
}
function applyReroll(state, ageBand, today, seed) {
  if (!canReroll(state, today)) return null;
  const { question, questionId } = selectNewQuestion(state, ageBand, seed);
  return {
    question,
    nextState: {
      ...state,
      currentQuestionId: questionId,
      currentQuestionDate: today,
      rerollsUsedToday: state.rerollsUsedToday + 1,
      askedQuestionIds: [...state.askedQuestionIds, questionId],
    },
  };
}
