"use strict";
// AUTO-GENERATED by sync-economy-module.js — do not edit by hand.
/** Canonical idempotency key builders — keep in sync with economy callables. */
Object.defineProperty(exports, "__esModule", { value: true });
exports.lessonCompleteKey = lessonCompleteKey;
exports.wellAnswerKey = wellAnswerKey;
exports.fishingClaimKey = fishingClaimKey;
exports.craftStartKey = craftStartKey;
exports.craftCollectKey = craftCollectKey;
exports.rodEquipKey = rodEquipKey;
exports.practiceKey = practiceKey;
exports.baitCraftKey = baitCraftKey;
exports.diaryKey = diaryKey;
exports.castCreateKey = castCreateKey;
exports.castCancelKey = castCancelKey;
exports.wellAssignKey = wellAssignKey;
exports.wellRerollKey = wellRerollKey;
exports.purchaseVerifyKey = purchaseVerifyKey;
exports.fishingResetKey = fishingResetKey;
function lessonCompleteKey(lessonId) {
  return `lesson_complete:${lessonId}`;
}
function wellAnswerKey(localDate) {
  return `well_answer:${localDate}`;
}
function fishingClaimKey(castId) {
  return `fishing_claim:${castId}`;
}
function craftStartKey(rodId) {
  return `craft_start:${rodId}`;
}
function craftCollectKey(rodId) {
  return `craft_collect:${rodId}`;
}
function rodEquipKey(rodId) {
  return `rod_equip:${rodId}`;
}
function practiceKey(localDate, kind) {
  return `practice:${localDate}:${kind}`;
}
function baitCraftKey(requestId) {
  return `bait_craft:${requestId}`;
}
function diaryKey(requestId) {
  return `diary:${requestId}`;
}
function castCreateKey(requestId) {
  return `cast_create:${requestId}`;
}
function castCancelKey(castId) {
  return `cast_cancel:${castId}`;
}
function wellAssignKey(localDate) {
  return `well_assign:${localDate}`;
}
function wellRerollKey(localDate, requestId) {
  return `well_reroll:${localDate}:${requestId}`;
}
function purchaseVerifyKey(transactionId) {
  return `purchase_verify:${transactionId}`;
}
function fishingResetKey(utcDate) {
  return `fishing_reset:${utcDate}`;
}
