"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.COMPACT_TAIL_LOG_THRESHOLD =
  exports.COMPACT_TAIL_HARD_LIMIT =
  exports.COMPACT_KEEP_TAIL_ENTRIES =
  exports.COMPACT_WHEN_TOTAL_ENTRIES =
  exports.MAX_LEDGER_READS_PER_TX =
    void 0;
// AUTO-GENERATED by sync-economy-module.js — do not edit by hand.
/** Firestore tx read cap — leave headroom for user + idempotency reads. */
exports.MAX_LEDGER_READS_PER_TX = 450;
/** Proactive compaction when total ledger rows exceed this count. */
exports.COMPACT_WHEN_TOTAL_ENTRIES = 350;
/** Ledger rows left unread after compaction (tail query). */
exports.COMPACT_KEEP_TAIL_ENTRIES = 100;
/** Refuse commit when tail alone exceeds this (force compaction). */
exports.COMPACT_TAIL_HARD_LIMIT = 300;
/** Log/metric hint when tail exceeds this size. */
exports.COMPACT_TAIL_LOG_THRESHOLD = 200;
