"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.COMPACT_TAIL_HARD_LIMIT = exports.MAX_LEDGER_READS_PER_TX = void 0;
exports.computeProjectionFromLedgerState = computeProjectionFromLedgerState;
exports.computeEconomyProjectionInTransaction = computeEconomyProjectionInTransaction;
// AUTO-GENERATED by sync-economy-module.js — do not edit by hand.
const compactionConstants_1 = require("./compactionConstants");
const foldLedger_1 = require("./foldLedger");
const types_1 = require("./types");
const types_2 = require("./types");
var compactionConstants_2 = require("./compactionConstants");
Object.defineProperty(exports, "MAX_LEDGER_READS_PER_TX", {
  enumerable: true,
  get: function () {
    return compactionConstants_2.MAX_LEDGER_READS_PER_TX;
  },
});
Object.defineProperty(exports, "COMPACT_TAIL_HARD_LIMIT", {
  enumerable: true,
  get: function () {
    return compactionConstants_2.COMPACT_TAIL_HARD_LIMIT;
  },
});
function assertSolvencyFromFold(sums, context) {
  if (sums.currentWonder < 0 || sums.storedWonder < 0 || sums.parts < 0) {
    throw new types_1.EconomyError(
      "INSUFFICIENT_WONDER",
      "Ledger fold would produce negative balances",
      {
        currentWonder: sums.currentWonder,
        storedWonder: sums.storedWonder,
        parts: sums.parts,
        ...context,
      },
    );
  }
}
function computeProjectionFromLedgerState(input) {
  const projection = (0, foldLedger_1.projectionFromCheckpointAndEntries)(
    input.checkpoint,
    input.tailEntries,
    input.pendingEntry,
  );
  const tailWithPending = [...input.tailEntries, input.pendingEntry];
  const baseSums = input.checkpoint
    ? { ...input.checkpoint.foldSums }
    : (0, foldLedger_1.emptyLedgerFoldSums)();
  const mergedSums = (0, foldLedger_1.mergeFoldSums)(
    baseSums,
    tailWithPending.length > 0
      ? (0, foldLedger_1.foldLedgerEntries)(tailWithPending)
      : (0, foldLedger_1.emptyLedgerFoldSums)(),
  );
  assertSolvencyFromFold(mergedSums, {
    tailEntryCount: input.tailEntries.length,
    usedCheckpoint: !!input.checkpoint,
  });
  const totalCommittedEntryCount =
    (input.checkpoint?.foldedEntryCount ?? 0) + input.tailEntries.length;
  return {
    projection,
    meta: {
      tailEntryCount: input.tailEntries.length,
      usedCheckpoint: !!input.checkpoint,
      totalCommittedEntryCount,
    },
  };
}
/**
 * Fold committed ledger rows plus the pending entry (not yet visible to collection queries in-tx).
 * Uses checkpoint + tail query when checkpoint exists; otherwise full collection scan.
 */
async function computeEconomyProjectionInTransaction(tx, userRef, pendingEntry) {
  const checkpointRef = userRef
    .collection("economyLedgerCheckpoint")
    .doc(types_2.ECONOMY_LEDGER_CHECKPOINT_DOC_ID);
  const checkpointSnap = await tx.get(checkpointRef);
  const checkpoint = checkpointSnap.exists ? checkpointSnap.data() : null;
  if (!checkpoint) {
    const ledgerSnap = await tx.get(userRef.collection("economyLedger"));
    if (ledgerSnap.size >= compactionConstants_1.MAX_LEDGER_READS_PER_TX) {
      throw new types_1.EconomyError(
        "LEDGER_READ_LIMIT",
        `User ledger has ${ledgerSnap.size} entries; running totals required before ${compactionConstants_1.MAX_LEDGER_READS_PER_TX}`,
        { ledgerEntryCount: ledgerSnap.size },
      );
    }
    const entries = ledgerSnap.docs.map((doc) => doc.data());
    entries.push(pendingEntry);
    const sums = (0, foldLedger_1.foldLedgerEntries)(entries);
    assertSolvencyFromFold(sums, { ledgerEntryCount: ledgerSnap.size });
    return {
      projection: (0, foldLedger_1.projectionFromLedgerEntries)(entries),
      meta: {
        tailEntryCount: ledgerSnap.size,
        usedCheckpoint: false,
        totalCommittedEntryCount: ledgerSnap.size,
      },
    };
  }
  const tailSnap = await tx.get(
    userRef
      .collection("economyLedger")
      .where("timestamp", ">", checkpoint.foldedThroughTimestamp)
      .orderBy("timestamp", "asc"),
  );
  if (tailSnap.size >= compactionConstants_1.COMPACT_TAIL_HARD_LIMIT) {
    throw new types_1.EconomyError(
      "LEDGER_READ_LIMIT",
      `User ledger tail has ${tailSnap.size} entries; compaction required before ${compactionConstants_1.COMPACT_TAIL_HARD_LIMIT}`,
      { tailEntryCount: tailSnap.size, foldedEntryCount: checkpoint.foldedEntryCount },
    );
  }
  const tailEntries = tailSnap.docs.map((doc) => doc.data());
  return computeProjectionFromLedgerState({ checkpoint, tailEntries, pendingEntry });
}
