"use strict";
var __importDefault =
  (this && this.__importDefault) ||
  function (mod) {
    return mod && mod.__esModule ? mod : { default: mod };
  };
Object.defineProperty(exports, "__esModule", { value: true });
// AUTO-GENERATED by sync-economy-module.js — do not edit by hand.
const strict_1 = __importDefault(require("node:assert/strict"));
const node_test_1 = __importDefault(require("node:test"));
const foldBaitInventory_1 = require("./foldBaitInventory");
function entry(overrides) {
  return {
    id: "ledger_1",
    uid: "user_a",
    timestamp: Date.now(),
    actionType: "bait_craft",
    source: "bait_craft",
    deltaCurrentWonder: 0,
    deltaStoredWonder: 0,
    deltaParts: 0,
    deltaMaterials: {},
    idempotencyKey: "bait:1",
    metadata: {},
    schemaVersion: 1,
    ...overrides,
  };
}
(0, node_test_1.default)("baitKeyFromCraftMetadata prefers baitKey over tier", () => {
  strict_1.default.equal(
    (0, foldBaitInventory_1.baitKeyFromCraftMetadata)({ baitKey: "scale_bait", tier: "basic" }),
    "scale_bait",
  );
});
(0, node_test_1.default)("baitKeyFromCraftMetadata maps tier when baitKey absent", () => {
  strict_1.default.equal(
    (0, foldBaitInventory_1.baitKeyFromCraftMetadata)({ tier: "rare" }),
    "scale_bait",
  );
});
(0, node_test_1.default)("foldBaitInventoryFromLedger crafts and deducts consumable baits", () => {
  const folded = (0, foldBaitInventory_1.foldBaitInventoryFromLedger)([
    entry({ metadata: { baitKey: "feather_bait" } }),
    entry({
      id: "ledger_2",
      actionType: "cast_create",
      source: "fishing_catch",
      metadata: { baitUsed: "feather_bait", baitDeducted: true },
    }),
    entry({
      id: "ledger_3",
      metadata: { tier: "rare" },
    }),
  ]);
  strict_1.default.deepEqual(folded, {
    feather_bait: 0,
    scale_bait: 1,
    glimmerdust_bait: 0,
    random_bait: 0,
  });
});
(0, node_test_1.default)("foldBaitInventoryFromLedger ignores random_bait cast_create", () => {
  const folded = (0, foldBaitInventory_1.foldBaitInventoryFromLedger)([
    entry({
      id: "ledger_cast",
      actionType: "cast_create",
      source: "fishing_catch",
      metadata: { baitUsed: "random_bait", baitDeducted: false },
    }),
  ]);
  strict_1.default.deepEqual(folded, {
    feather_bait: 0,
    scale_bait: 0,
    glimmerdust_bait: 0,
    random_bait: 0,
  });
});
