// AUTO-GENERATED by sync-fishing-module.js — do not edit by hand.
import type {
  BaitTier,
  ElementType,
  EpicFishingRodId,
  FishingClaim,
  FishingPityState,
  FishingRodId,
  PoolTier,
} from "./types";
import { DEFAULT_FISHING_PITY } from "./types";
import { pickWeightedIndex, rollBelow } from "./random";
import { rodTypeKeyForId } from "./rodCatalog";
import {
  DUPLICATE_CATCH_MESSAGES,
  fillCreatureName,
  MISS_CHANCE_MESSAGES,
  MISS_WONDER_GATE_MESSAGES,
  NEW_CATCH_MESSAGES,
  pickMessageVariant,
} from "./fishingOutcomeMessages";

/** Wonder-scaled catch bases — Sheet D bait bonuses apply on top (not these legacy baitBonus fields). */
export const ENCOUNTER_RATES = {
  common: { base: 0.55, wonderDivisor: 600, maxNoBait: 0.7 },
  rareElement: { base: 0.14, wonderDivisor: 500, maxNoBait: 0.2 },
  rareAny: { base: 0.06, wonderDivisor: 600, maxNoBait: 0.1 },
  epicElement: { base: 0.03, wonderDivisor: 700, maxNoBait: 0.07 },
} as const;

/** Sheet A discrete wonder-gate ladder (not linear gateStep). */
export const WONDER_GATE_LADDER = [0, 40, 65, 90] as const;

/** Sheet D — catch% additive bonuses by domain bait tier (basic/mid/premium → basic/rare/epic). */
export const SHEET_D_CATCH_BONUS: Record<BaitTier, number> = {
  basic: 0.05,
  rare: 0.12,
  epic: 0.2,
};

/** Sheet D — wonder-gate tiers removed by bait. */
export const SHEET_D_TIERS_REMOVED: Record<BaitTier, number> = {
  basic: 0,
  rare: 1,
  epic: 2,
};

export const MISS_CONSOLATION = {
  common: { materials: 1, wonder: 0 },
  rare: { materials: 1, wonder: 0 },
  epic: { materials: 2, wonder: 0 },
} as const;

export const DUPLICATE_CONSOLATION = {
  common: { materials: 1, wonder: 1, spiritEcho: false },
  rare: { materials: 2, wonder: 2, spiritEcho: false },
  epic: { materials: 3, wonder: 4, spiritEcho: true },
  poolComplete: { materials: 0, wonder: 10, spiritEcho: true },
} as const;

/** Sheet C — per-creature base weights by rod weight profile × sub_tier. */
export type CreatureSubTier = "uniform" | "common-rare" | "mid-rare" | "top-rare";

export type SheetCWeightProfile = "basic" | "rare" | "epic13" | "epic12";

export const SHEET_C_BASE_WEIGHTS: Record<SheetCWeightProfile, Record<CreatureSubTier, number>> = {
  basic: { uniform: 1, "common-rare": 1, "mid-rare": 1, "top-rare": 1 },
  rare: { uniform: 1, "common-rare": 23, "mid-rare": 6, "top-rare": 4 },
  /** epic1 / epic2 — 13-creature pools */
  epic13: { uniform: 1, "common-rare": 3, "mid-rare": 3, "top-rare": 2 },
  /** epic3 / epic4 — 12-creature pools */
  epic12: { uniform: 1, "common-rare": 18, "mid-rare": 15, "top-rare": 10 },
};

export const CHANCE_MISS_PITY_THRESHOLD = 10;
export const EPIC_TOP_RARE_DRY_THRESHOLD = 20;
export const EPIC_TOP_RARE_PITY_STEP = 0.15;

export type CreatureRef = {
  creatureTypeId: string;
  displayName: string;
  poolTier: PoolTier;
  elementType: ElementType;
  rodRequired: string;
  peakWonderGate: number;
  sub_tier: CreatureSubTier;
};

export function sheetDCatchBonus(baitTier: BaitTier | null): number {
  if (baitTier == null) return 0;
  return SHEET_D_CATCH_BONUS[baitTier];
}

export function sheetDTiersRemoved(baitTier: BaitTier | null): number {
  if (baitTier == null) return 0;
  return SHEET_D_TIERS_REMOVED[baitTier];
}

/**
 * Sheet D gate unlock: walk WONDER_GATE_LADDER back by removedTiers.
 * 1.1 clamp: rare-element base 40W never drops (removedTiers have no gate effect).
 */
export function effectiveWonderGate(peakWonderGate: number, baitTier: BaitTier | null): number {
  if (peakWonderGate === 40) return 40;

  const baseIndex = (WONDER_GATE_LADDER as readonly number[]).indexOf(peakWonderGate);
  if (baseIndex < 0) return peakWonderGate;

  const targetIndex = Math.max(0, baseIndex - sheetDTiersRemoved(baitTier));
  return WONDER_GATE_LADDER[targetIndex]!;
}

export function catchChance(
  poolTier: PoolTier,
  elementType: ElementType,
  currentWonder: number,
  baitTier: BaitTier | null,
): number {
  const r =
    elementType === "any"
      ? ENCOUNTER_RATES.rareAny
      : poolTier === "common"
        ? ENCOUNTER_RATES.common
        : poolTier === "rare"
          ? ENCOUNTER_RATES.rareElement
          : ENCOUNTER_RATES.epicElement;
  const wonderBonus = Math.min(currentWonder / r.wonderDivisor, r.maxNoBait - r.base);
  const base = Math.min(r.base + wonderBonus, r.maxNoBait);
  return Math.min(base + sheetDCatchBonus(baitTier), 1);
}

export function poolForRod(rodId: FishingRodId, catalog: CreatureRef[]): CreatureRef[] {
  const rodTypeKey = rodTypeKeyForId(rodId);
  return catalog.filter((c) => c.rodRequired === rodTypeKey);
}

export function sheetCWeightProfileForRod(rodId: FishingRodId): SheetCWeightProfile {
  const key = rodTypeKeyForId(rodId);
  if (key === "basic") return "basic";
  if (key === "epic1" || key === "epic2") return "epic13";
  if (key === "epic3" || key === "epic4") return "epic12";
  return "rare";
}

export function isEpicFishingRodId(rodId: FishingRodId): rodId is EpicFishingRodId {
  return (
    rodId === "epic_fire" ||
    rodId === "epic_water" ||
    rodId === "epic_wind" ||
    rodId === "epic_electric"
  );
}

/** Casts past the 20-cast threshold → multiplier on each top-rare creature weight. */
export function epicTopRarePityMultiplier(dryStreak: number): number {
  const past = Math.max(0, dryStreak - EPIC_TOP_RARE_DRY_THRESHOLD);
  return 1 + EPIC_TOP_RARE_PITY_STEP * past;
}

export function baseWeightForCreature(
  creature: CreatureRef,
  profile: SheetCWeightProfile,
  topRareMultiplier = 1,
): number {
  const table = SHEET_C_BASE_WEIGHTS[profile];
  const sub = creature.sub_tier in table ? creature.sub_tier : "uniform";
  const base = table[sub] ?? 1;
  if (sub === "top-rare" && topRareMultiplier !== 1) {
    return base * topRareMultiplier;
  }
  return base;
}

/** Per-creature weights for an eligible candidate list (Sheet C + optional epic pity). */
export function creatureWeights(
  candidates: CreatureRef[],
  rodId: FishingRodId,
  topRareMultiplier = 1,
): number[] {
  const profile = sheetCWeightProfileForRod(rodId);
  return candidates.map((c) => baseWeightForCreature(c, profile, topRareMultiplier));
}

/** P(top-rare | catch) for regression / Sheet E arithmetic checks. */
export function topRareShareGivenCatch(
  candidates: CreatureRef[],
  rodId: FishingRodId,
  dryStreak: number,
): number {
  const mult = epicTopRarePityMultiplier(dryStreak);
  const weights = creatureWeights(candidates, rodId, mult);
  let total = 0;
  let top = 0;
  for (let i = 0; i < candidates.length; i += 1) {
    total += weights[i]!;
    if (candidates[i]!.sub_tier === "top-rare") top += weights[i]!;
  }
  return total > 0 ? top / total : 0;
}

export function selectCandidate(
  pool: CreatureRef[],
  caughtIds: Set<string>,
  seed: string,
  rodId: FishingRodId,
  topRareMultiplier = 1,
): CreatureRef {
  const unseen = pool.filter((c) => !caughtIds.has(c.creatureTypeId));
  const candidates = unseen.length > 0 ? unseen : pool;
  if (candidates.length === 0) {
    throw new Error("Empty creature pool");
  }
  const weights = creatureWeights(candidates, rodId, topRareMultiplier);
  return candidates[pickWeightedIndex(seed, weights)]!;
}

export function rarityIndicatorForTier(tier: PoolTier): FishingClaim["rarityIndicator"] {
  if (tier === "common") return "common";
  if (tier === "rare") return "rare";
  return "epic";
}

export function normalizeFishingPity(pity?: FishingPityState | null): FishingPityState {
  return {
    consecutiveChanceMisses: pity?.consecutiveChanceMisses ?? 0,
    epicTopRareDryStreak: { ...(pity?.epicTopRareDryStreak ?? {}) },
  };
}

export function nextFishingPityAfterClaim(input: {
  prev: FishingPityState;
  rodId: FishingRodId;
  outcome: FishingClaim["outcome"];
  reason?: string;
  creatureSubTier?: CreatureSubTier;
}): FishingPityState {
  const next = normalizeFishingPity(input.prev);

  if (input.reason === "wonder_gate") {
    // Excluded entirely — neither increments nor resets consecutiveChanceMisses.
  } else if (input.outcome === "miss") {
    next.consecutiveChanceMisses += 1;
  } else {
    next.consecutiveChanceMisses = 0;
  }

  if (isEpicFishingRodId(input.rodId) && input.reason !== "wonder_gate") {
    const landedTopRare =
      (input.outcome === "catch" || input.outcome === "duplicate") &&
      input.creatureSubTier === "top-rare";
    if (landedTopRare) {
      next.epicTopRareDryStreak[input.rodId] = 0;
    } else {
      next.epicTopRareDryStreak[input.rodId] =
        (input.prev.epicTopRareDryStreak[input.rodId] ?? 0) + 1;
    }
  }

  return next;
}

export type ResolveClaimInput = {
  claimId: string;
  encounterId: string;
  userId: string;
  castId: string;
  rodId: FishingRodId;
  baitTier: BaitTier | null;
  currentWonderAtClaim: number;
  caughtIds: Set<string>;
  creatureCatalog: CreatureRef[];
  fishingPity?: FishingPityState | null;
  now?: number;
};

export type ResolveFishingClaimResult = {
  claim: FishingClaim;
  nextFishingPity: FishingPityState;
};

export function resolveFishingClaim(input: ResolveClaimInput): ResolveFishingClaimResult {
  const {
    claimId,
    encounterId,
    userId,
    castId,
    rodId,
    baitTier,
    currentWonderAtClaim,
    caughtIds,
    creatureCatalog,
    now = Date.now(),
  } = input;

  const pity = normalizeFishingPity(input.fishingPity ?? DEFAULT_FISHING_PITY);
  const dryStreak = isEpicFishingRodId(rodId) ? (pity.epicTopRareDryStreak[rodId] ?? 0) : 0;
  const topRareMultiplier = epicTopRarePityMultiplier(dryStreak);

  const pool = poolForRod(rodId, creatureCatalog).filter(
    (c) => currentWonderAtClaim >= effectiveWonderGate(c.peakWonderGate, baitTier),
  );

  if (pool.length === 0) {
    const claim: FishingClaim = {
      id: claimId,
      encounterId,
      userId,
      claimedAt: now,
      currentWonderAtClaim,
      outcome: "miss",
      poolTier: "common",
      rarityIndicator: "common",
      wonderAwarded: 0,
      materialsAwarded: 1,
      spiritMessage: pickMessageVariant(`${userId}:${castId}:msg:gate`, MISS_WONDER_GATE_MESSAGES),
      metadata: { castId, reason: "wonder_gate" },
    };
    return {
      claim,
      nextFishingPity: nextFishingPityAfterClaim({
        prev: pity,
        rodId,
        outcome: "miss",
        reason: "wonder_gate",
      }),
    };
  }

  const primaryTier = pool[0]?.poolTier ?? "common";
  const element = pool[0]?.elementType ?? "any";
  const chance = catchChance(primaryTier, element, currentWonderAtClaim, baitTier);
  const rollSeed = `${userId}:${castId}:catch`;
  const guaranteedCatch = pity.consecutiveChanceMisses >= CHANCE_MISS_PITY_THRESHOLD;

  if (!guaranteedCatch && !rollBelow(rollSeed, chance)) {
    const miss = MISS_CONSOLATION[primaryTier as keyof typeof MISS_CONSOLATION];
    const claim: FishingClaim = {
      id: claimId,
      encounterId,
      userId,
      claimedAt: now,
      currentWonderAtClaim,
      outcome: "miss",
      poolTier: primaryTier,
      rarityIndicator: rarityIndicatorForTier(primaryTier),
      wonderAwarded: miss.wonder,
      materialsAwarded: miss.materials,
      spiritMessage: pickMessageVariant(`${userId}:${castId}:msg:miss`, MISS_CHANCE_MESSAGES),
      metadata: { castId, reason: "chance" },
    };
    return {
      claim,
      nextFishingPity: nextFishingPityAfterClaim({
        prev: pity,
        rodId,
        outcome: "miss",
        reason: "chance",
      }),
    };
  }

  const creature = selectCandidate(
    pool,
    caughtIds,
    `${rollSeed}:creature`,
    rodId,
    topRareMultiplier,
  );
  const isDuplicate = caughtIds.has(creature.creatureTypeId);
  const msgSeed = `${userId}:${castId}:msg`;

  if (isDuplicate) {
    const dup = DUPLICATE_CONSOLATION[creature.poolTier as keyof typeof DUPLICATE_CONSOLATION];
    const claim: FishingClaim = {
      id: claimId,
      encounterId,
      userId,
      claimedAt: now,
      currentWonderAtClaim,
      outcome: "duplicate",
      creatureTypeId: creature.creatureTypeId,
      creatureDisplayName: creature.displayName,
      poolTier: creature.poolTier,
      rarityIndicator: rarityIndicatorForTier(creature.poolTier),
      wonderAwarded: dup.wonder,
      materialsAwarded: dup.materials,
      spiritMessage: fillCreatureName(
        pickMessageVariant(`${msgSeed}:dup`, DUPLICATE_CATCH_MESSAGES),
        creature.displayName,
      ),
      metadata: {
        castId,
        spiritEcho: "spiritEcho" in dup ? dup.spiritEcho : false,
        guaranteedCatch,
      },
    };
    return {
      claim,
      nextFishingPity: nextFishingPityAfterClaim({
        prev: pity,
        rodId,
        outcome: "duplicate",
        creatureSubTier: creature.sub_tier,
      }),
    };
  }

  const claim: FishingClaim = {
    id: claimId,
    encounterId,
    userId,
    claimedAt: now,
    currentWonderAtClaim,
    outcome: "catch",
    creatureTypeId: creature.creatureTypeId,
    creatureDisplayName: creature.displayName,
    poolTier: creature.poolTier,
    rarityIndicator: rarityIndicatorForTier(creature.poolTier),
    wonderAwarded: 0,
    materialsAwarded: 0,
    spiritMessage: fillCreatureName(
      pickMessageVariant(`${msgSeed}:catch`, NEW_CATCH_MESSAGES),
      creature.displayName,
    ),
    metadata: { castId, guaranteedCatch },
  };
  return {
    claim,
    nextFishingPity: nextFishingPityAfterClaim({
      prev: pity,
      rodId,
      outcome: "catch",
      creatureSubTier: creature.sub_tier,
    }),
  };
}

/** @deprecated Prefer DUPLICATE_CATCH_MESSAGES via resolveFishingClaim. */
export function spiritEchoForDuplicate(displayName: string): string {
  return fillCreatureName(DUPLICATE_CATCH_MESSAGES[0], displayName);
}

export { toClientClaimSummary, toFishingClaimPresentation } from "./fishingClaimPresentation";
export type { FishingClaimPresentation } from "./fishingClaimPresentation";
