// AUTO-GENERATED by sync-fishing-module.js — do not edit by hand.
import type { FishingClaim, PoolTier } from "./types";
import type { FishingClaimClientSummary } from "./economy/callableResponses";

export type FishingClaimPresentation = {
  outcome: FishingClaim["outcome"];
  caughtCreature: { id: string; displayName: string } | null;
  rarity: FishingClaim["rarityIndicator"];
  poolTier: PoolTier;
  wonderDelta: number;
  materialDelta: number;
  duplicateReward: { wonder: number; materials: number } | null;
  consolationReward: { wonder: number; materials: number; spiritMessage?: string } | null;
  spiritMessage?: string;
};

export function toFishingClaimPresentation(claim: FishingClaim): FishingClaimPresentation {
  const caughtCreature =
    claim.creatureTypeId && claim.creatureDisplayName
      ? { id: claim.creatureTypeId, displayName: claim.creatureDisplayName }
      : null;

  const duplicateReward =
    claim.outcome === "duplicate"
      ? { wonder: claim.wonderAwarded, materials: claim.materialsAwarded }
      : null;

  const consolationReward =
    claim.outcome === "miss"
      ? {
          wonder: claim.wonderAwarded,
          materials: claim.materialsAwarded,
          spiritMessage: claim.spiritMessage,
        }
      : null;

  return {
    outcome: claim.outcome,
    caughtCreature,
    rarity: claim.rarityIndicator,
    poolTier: claim.poolTier,
    wonderDelta: claim.wonderAwarded,
    materialDelta: claim.materialsAwarded,
    duplicateReward,
    consolationReward,
    spiritMessage: claim.spiritMessage,
  };
}

/** Client-safe summary — no percentages exposed. */
export function toClientClaimSummary(claim: FishingClaim): FishingClaimClientSummary {
  const summary: FishingClaimClientSummary = {
    outcome: claim.outcome,
    rarityIndicator: claim.rarityIndicator,
    wonderAwarded: claim.wonderAwarded,
    materialsAwarded: claim.materialsAwarded,
    claimedAt: claim.claimedAt,
  };
  if (claim.creatureTypeId != null) summary.creatureTypeId = claim.creatureTypeId;
  if (claim.creatureDisplayName != null) summary.creatureDisplayName = claim.creatureDisplayName;
  if (claim.spiritMessage != null) summary.spiritMessage = claim.spiritMessage;

  const reason = claim.metadata?.reason;
  if (typeof reason === "string" && reason.length > 0) {
    summary.metadata = { reason };
  }

  return summary;
}
