// AUTO-GENERATED by sync-wonder-module.js — do not edit by hand.
import type { WonderAccount, WonderSource, WonderTransaction } from "./types";

export type WonderPool = "current" | "stored" | "both";

export type ApplyWonderEarnInput = {
  account: WonderAccount;
  source: WonderSource;
  amount: number;
  transactionId: string;
  metadata?: Record<string, unknown>;
  /** Rod investments only touch storedWonder */
  pool?: WonderPool;
};

export type ApplyWonderSpendInput = {
  account: WonderAccount;
  source: WonderSource;
  amount: number;
  transactionId: string;
  metadata?: Record<string, unknown>;
  pool: "current" | "stored";
};

export type WonderLedgerResult = {
  account: WonderAccount;
  transaction: WonderTransaction;
};

function cloneAccount(account: WonderAccount): WonderAccount {
  return { ...account };
}

/** Earn Wonder — default credits both current and stored pools. */
export function applyWonderEarn(input: ApplyWonderEarnInput): WonderLedgerResult {
  const { account, source, amount, transactionId, metadata = {}, pool = "both" } = input;
  if (amount <= 0) throw new Error("Earn amount must be positive");

  const next = cloneAccount(account);
  const now = Date.now();

  if (pool === "current" || pool === "both") {
    next.currentWonder += amount;
  }
  if (pool === "stored" || pool === "both") {
    next.storedWonder += amount;
    next.lifetimeWonderEarned += amount;
  }
  next.updatedAt = now;

  return {
    account: next,
    transaction: {
      id: transactionId,
      userId: account.userId,
      timestamp: now,
      source,
      amount,
      metadata,
    },
  };
}

/** Spend from exactly one pool — never mix. */
export function applyWonderSpend(input: ApplyWonderSpendInput): WonderLedgerResult {
  const { account, source, amount, transactionId, metadata = {}, pool } = input;
  if (amount <= 0) throw new Error("Spend amount must be positive");

  const balance = pool === "current" ? account.currentWonder : account.storedWonder;
  if (balance < amount) {
    throw new Error(`Insufficient ${pool} Wonder`);
  }

  const next = cloneAccount(account);
  const now = Date.now();

  if (pool === "current") {
    next.currentWonder -= amount;
  } else {
    next.storedWonder -= amount;
  }
  next.updatedAt = now;

  return {
    account: next,
    transaction: {
      id: transactionId,
      userId: account.userId,
      timestamp: now,
      source,
      amount: -amount,
      metadata: { ...metadata, pool },
    },
  };
}

/** Rod crafting invests storedWonder only. */
export function investStoredWonderForRod(
  account: WonderAccount,
  transactionId: string,
  storedWonderCost: number,
  rodId: string,
): WonderLedgerResult {
  return applyWonderSpend({
    account,
    source: "rod_craft_investment",
    amount: storedWonderCost,
    transactionId,
    pool: "stored",
    metadata: { rodId },
  });
}

/** Bait crafting spends currentWonder only. */
export function spendCurrentWonderForBait(
  account: WonderAccount,
  transactionId: string,
  currentWonderCost: number,
  baitTier: string,
): WonderLedgerResult {
  return applyWonderSpend({
    account,
    source: "bait_craft",
    amount: currentWonderCost,
    transactionId,
    pool: "current",
    metadata: { baitTier },
  });
}

export function createEmptyWonderAccount(userId: string): WonderAccount {
  return {
    userId,
    currentWonder: 0,
    storedWonder: 0,
    lifetimeWonderEarned: 0,
    updatedAt: Date.now(),
  };
}

/** Migrate legacy single-pool totalWonder into split pools. */
export function migrateFromLegacyTotalWonder(userId: string, totalWonder: number): WonderAccount {
  return {
    userId,
    currentWonder: totalWonder,
    storedWonder: totalWonder,
    lifetimeWonderEarned: totalWonder,
    updatedAt: Date.now(),
  };
}
