// AUTO-GENERATED by sync-fishing-module.js — do not edit by hand.
export { filterCreaturesByRodPermission } from "./rodFishingAccess";
import type { FishingRodId } from "./_sanctuaryTypes";

export function assertRodOwnedForCast(rodId: FishingRodId, state: string | undefined): void {
  if (state !== "ready" && state !== "equipped") {
    throw new Error(`Rod ${rodId} is not owned for fishing`);
  }
}
