"use strict";
// AUTO-GENERATED by sync-child-profile-module.js — do not edit by hand.
/**
 * Shared Deep Check scoring — continuous Expression (A) + Driver (B) axes.
 * Maps to DisplayArchetypeName via resolveDisplayArchetypeFromAxes.
 *
 * `recentDeepChecks` Firestore field holds a **shared** QC+DC map trail
 * (newest-first, capped) despite the historical field name.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MAP_CHECK_HISTORY_CAP =
  exports.DEEP_CHECK_HISTORY_CAP =
  exports.DEEP_CHECK_SCENARIO_COUNT =
    void 0;
exports.clampAxis = clampAxis;
exports.normalizeMapCheckSource = normalizeMapCheckSource;
exports.isDeepCheckAxisPair = isDeepCheckAxisPair;
exports.primaryArchetypeFromDisplay = primaryArchetypeFromDisplay;
exports.scoreDeepCheck = scoreDeepCheck;
exports.prependRecentDeepCheck = prependRecentDeepCheck;
exports.mapArchetypeCheckToTrailPoint = mapArchetypeCheckToTrailPoint;
exports.rebuildRecentMapChecks = rebuildRecentMapChecks;
exports.parseRecentDeepChecks = parseRecentDeepChecks;
const archetypeCaptionBank_1 = require("./archetypeCaptionBank");
const archetypeQuickCheck_1 = require("./archetypeQuickCheck");
/** Must match Deep Check UI scenario count. */
exports.DEEP_CHECK_SCENARIO_COUNT = 5;
/** Max map-trail points retained per child (Quick + Deep shared). */
exports.DEEP_CHECK_HISTORY_CAP = 5;
/** Alias — same cap as DEEP_CHECK_HISTORY_CAP (shared QC+DC trail). */
exports.MAP_CHECK_HISTORY_CAP = exports.DEEP_CHECK_HISTORY_CAP;
function clampAxis(value) {
  if (!Number.isFinite(value)) return 50;
  return Math.min(100, Math.max(0, value));
}
function normalizeMapCheckSource(source) {
  return source === "quick" ? "quick" : "deep";
}
function isDeepCheckAxisPair(value) {
  if (!value || typeof value !== "object") return false;
  const v = value;
  return (
    typeof v.expression === "number" &&
    Number.isFinite(v.expression) &&
    typeof v.driver === "number" &&
    Number.isFinite(v.driver)
  );
}
/** Discrete archetype for child.archetype / narrative compatibility. */
function primaryArchetypeFromDisplay(displayName) {
  switch (displayName) {
    case "Still Pond":
      return "wall";
    case "Quiet Storm":
      return "storm";
    case "Storm Child":
      return "spark";
    case "Ember Child":
      return "spark";
    case "Weather Child":
      return "wall";
  }
}
/**
 * Average five Expression/Driver pairs → axes + display name.
 */
function scoreDeepCheck(answers) {
  if (answers.length !== exports.DEEP_CHECK_SCENARIO_COUNT) {
    throw new Error(
      `deepCheckAnswers must contain exactly ${exports.DEEP_CHECK_SCENARIO_COUNT} pairs`,
    );
  }
  let sumA = 0;
  let sumB = 0;
  for (const pair of answers) {
    sumA += clampAxis(pair.expression);
    sumB += clampAxis(pair.driver);
  }
  const axisA = Math.round((sumA / exports.DEEP_CHECK_SCENARIO_COUNT) * 10) / 10;
  const axisB = Math.round((sumB / exports.DEEP_CHECK_SCENARIO_COUNT) * 10) / 10;
  const displayArchetypeName = (0, archetypeCaptionBank_1.resolveDisplayArchetypeFromAxes)(
    axisA,
    axisB,
  );
  return {
    axisA,
    axisB,
    displayArchetypeName,
    primaryArchetype: primaryArchetypeFromDisplay(displayArchetypeName),
  };
}
/** Prepend a point and keep newest-first, capped (shared QC+DC trail). */
function prependRecentDeepCheck(existing, next, cap = exports.MAP_CHECK_HISTORY_CAP) {
  const prior = Array.isArray(existing) ? existing : [];
  return [next, ...prior].slice(0, cap);
}
function completedAtFromCheck(raw) {
  if (typeof raw.completedAt === "string" && raw.completedAt.trim()) {
    return raw.completedAt.trim();
  }
  const created = raw.createdAt;
  if (created && typeof created === "object" && "toDate" in created) {
    const d = created.toDate();
    if (d instanceof Date && !Number.isNaN(d.getTime())) return d.toISOString();
  }
  if (typeof created === "string" && created.trim()) return created.trim();
  return null;
}
/**
 * Map one archetypeChecks doc → trail point, or null if unusable.
 */
function mapArchetypeCheckToTrailPoint(raw) {
  const completedAt = completedAtFromCheck(raw);
  if (!completedAt) return null;
  if (raw.type === "deep") {
    if (typeof raw.axisA !== "number" || typeof raw.axisB !== "number") return null;
    if (!Number.isFinite(raw.axisA) || !Number.isFinite(raw.axisB)) return null;
    return {
      axisA: raw.axisA,
      axisB: raw.axisB,
      completedAt,
      source: "deep",
    };
  }
  if (raw.type === "quick") {
    if (!(0, archetypeQuickCheck_1.isDisplayArchetypeName)(raw.displayArchetypeName)) return null;
    const axes = (0, archetypeCaptionBank_1.axesFromDisplayArchetype)(raw.displayArchetypeName);
    return {
      axisA: axes.axisA,
      axisB: axes.axisB,
      completedAt,
      source: "quick",
    };
  }
  return null;
}
/**
 * Rebuild newest-first trail from archetypeChecks (already newest-first)
 * plus the point being written in this submit (not yet in the query).
 */
function rebuildRecentMapChecks(args) {
  const cap = args.cap ?? exports.MAP_CHECK_HISTORY_CAP;
  const fromExisting = [];
  for (const raw of args.existingChecksNewestFirst) {
    const point = mapArchetypeCheckToTrailPoint(raw);
    if (point) fromExisting.push(point);
  }
  return [args.newest, ...fromExisting].slice(0, cap);
}
function parseRecentDeepChecks(raw) {
  if (!Array.isArray(raw)) return [];
  const out = [];
  for (const item of raw) {
    if (!item || typeof item !== "object") continue;
    const p = item;
    if (
      typeof p.axisA === "number" &&
      typeof p.axisB === "number" &&
      typeof p.completedAt === "string"
    ) {
      out.push({
        axisA: p.axisA,
        axisB: p.axisB,
        completedAt: p.completedAt,
        source: normalizeMapCheckSource(p.source),
      });
    }
  }
  return out;
}
