"use strict";
// AUTO-GENERATED by sync-child-profile-module.js — do not edit by hand.
/**
 * Shared Quick Check scoring + poetic display names.
 * Keep storage truth (primary / tie metadata) separate from display labels.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DISPLAY_ARCHETYPE_RESULT_COPY =
  exports.DISPLAY_ARCHETYPE_NAMES =
  exports.QUICK_CHECK_ANSWER_COUNT =
    void 0;
exports.isDisplayArchetypeName = isDisplayArchetypeName;
exports.isQuickCheckArchetype = isQuickCheckArchetype;
exports.scoreQuickCheckTally = scoreQuickCheckTally;
exports.resolveDisplayArchetypeName = resolveDisplayArchetypeName;
/** Must match Quick Check UI question count (src/constants/archetypeDiagnostics.ts). */
exports.QUICK_CHECK_ANSWER_COUNT = 5;
exports.DISPLAY_ARCHETYPE_NAMES = [
  "Still Pond",
  "Ember Child",
  "Quiet Storm",
  "Storm Child",
  "Weather Child",
];
function isDisplayArchetypeName(value) {
  return typeof value === "string" && exports.DISPLAY_ARCHETYPE_NAMES.includes(value);
}
const ARCHETYPE_ORDER = ["storm", "wall", "spark"];
function isQuickCheckArchetype(value) {
  return value === "storm" || value === "wall" || value === "spark";
}
/** Majority wins; on tie, most-recent answer (last in array) wins for primary. Never null. */
function scoreQuickCheckTally(answers) {
  if (answers.length === 0) {
    throw new Error("quickCheckTally must not be empty");
  }
  const counts = {
    storm: 0,
    wall: 0,
    spark: 0,
  };
  for (const answer of answers) {
    counts[answer] += 1;
  }
  const max = Math.max(counts.storm, counts.wall, counts.spark);
  const leaders = ARCHETYPE_ORDER.filter((id) => counts[id] === max);
  const tieOccurred = leaders.length > 1;
  const primaryArchetype = tieOccurred
    ? ([...answers].reverse().find((a) => leaders.includes(a)) ?? leaders[0])
    : leaders[0];
  const tiedArchetypes = tieOccurred ? leaders : [];
  return {
    primaryArchetype,
    tieOccurred,
    tiedArchetypes,
    displayArchetypeName: resolveDisplayArchetypeName({
      primaryArchetype,
      tieOccurred,
      tiedArchetypes,
    }),
  };
}
function resolveDisplayArchetypeName(args) {
  if (!args.tieOccurred) {
    if (args.primaryArchetype === "storm") return "Storm Child";
    if (args.primaryArchetype === "wall") return "Still Pond";
    return "Ember Child";
  }
  const set = new Set(args.tiedArchetypes);
  const hasStorm = set.has("storm");
  const hasWall = set.has("wall");
  const hasSpark = set.has("spark");
  if (hasStorm && hasWall && hasSpark) return "Weather Child";
  if (hasStorm && hasWall) return "Quiet Storm";
  if (hasStorm && hasSpark) return "Storm Child";
  if (hasWall && hasSpark) return "Ember Child";
  // Degenerate tie fallback — should not happen with valid tallies.
  if (args.primaryArchetype === "storm") return "Storm Child";
  if (args.primaryArchetype === "wall") return "Still Pond";
  return "Ember Child";
}
var archetypeCaptionBank_1 = require("./archetypeCaptionBank");
Object.defineProperty(exports, "DISPLAY_ARCHETYPE_RESULT_COPY", {
  enumerable: true,
  get: function () {
    return archetypeCaptionBank_1.DISPLAY_ARCHETYPE_RESULT_COPY;
  },
});
