"use strict";
// AUTO-GENERATED by sync-child-profile-module.js — do not edit by hand.
/**
 * Shared child-slot access helpers (CREATE_CHILD_PROFILE_PLAN.md §3).
 * Keep Firestore rules logic in parity with these functions.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CHILD_INTEREST_ALLOWLIST = exports.CHILD_COMPANION_IDS = exports.HARD_CHILD_CAP = void 0;
exports.resolveAccountTier = resolveAccountTier;
exports.tierChildLimit = tierChildLimit;
exports.canAccessChild = canAccessChild;
exports.canCreateNextChild = canCreateNextChild;
exports.isChildCompanionId = isChildCompanionId;
exports.filterAllowedInterests = filterAllowedInterests;
exports.HARD_CHILD_CAP = 3;
/** Resolve account tier from existing subscription fields — no parallel subscriptionTier. */
function resolveAccountTier(subscription) {
  if (subscription?.isLifetime === true) {
    return "lifetime";
  }
  const status = subscription?.subscriptionStatus;
  if (status === "wooden" || status === "fiberglass" || status === "free") {
    return status;
  }
  return "free";
}
function tierChildLimit(tier) {
  switch (tier) {
    case "free":
      return 1;
    case "wooden":
    case "fiberglass":
    case "lifetime":
      return 3;
  }
}
/**
 * childOrder === 1 is always accessible — separate from the free-limit formula
 * so a missing/malformed subscription never locks out the grandfather child.
 */
function canAccessChild(childOrder, tier) {
  if (childOrder === 1) {
    return true;
  }
  if (!Number.isFinite(childOrder) || childOrder < 1) {
    return false;
  }
  return childOrder <= tierChildLimit(tier);
}
function canCreateNextChild(currentChildCount, tier) {
  if (currentChildCount >= exports.HARD_CHILD_CAP) {
    return { ok: false, reason: "hard_cap" };
  }
  if (currentChildCount >= tierChildLimit(tier)) {
    return { ok: false, reason: "tier_limit" };
  }
  return { ok: true, nextOrder: currentChildCount + 1 };
}
exports.CHILD_COMPANION_IDS = ["blackbird", "goldfinch", "butterfly", "pond_fish"];
function isChildCompanionId(value) {
  return typeof value === "string" && exports.CHILD_COMPANION_IDS.includes(value);
}
/** Pressed-flower interest allowlist — locked for v1 seal validation. */
exports.CHILD_INTEREST_ALLOWLIST = [
  "curious",
  "gentle",
  "adventurous",
  "creative",
  "thoughtful",
  "playful",
];
function filterAllowedInterests(raw) {
  if (!Array.isArray(raw)) return [];
  const allow = new Set(exports.CHILD_INTEREST_ALLOWLIST);
  const out = [];
  for (const item of raw) {
    if (typeof item !== "string") continue;
    if (!allow.has(item)) continue;
    if (out.includes(item)) continue;
    out.push(item);
    if (out.length >= 3) break;
  }
  return out;
}
