// AUTO-GENERATED by sync-child-profile-module.js — do not edit by hand.
/**
 * Shared Quick Check scoring + poetic display names.
 * Keep storage truth (primary / tie metadata) separate from display labels.
 */

export type QuickCheckArchetype = "storm" | "wall" | "spark";

/** Must match Quick Check UI question count (src/constants/archetypeDiagnostics.ts). */
export const QUICK_CHECK_ANSWER_COUNT = 5;

export type DisplayArchetypeName =
  | "Still Pond"
  | "Ember Child"
  | "Quiet Storm"
  | "Storm Child"
  | "Weather Child";

export const DISPLAY_ARCHETYPE_NAMES: readonly DisplayArchetypeName[] = [
  "Still Pond",
  "Ember Child",
  "Quiet Storm",
  "Storm Child",
  "Weather Child",
] as const;

export function isDisplayArchetypeName(value: unknown): value is DisplayArchetypeName {
  return (
    typeof value === "string" && (DISPLAY_ARCHETYPE_NAMES as readonly string[]).includes(value)
  );
}

export type QuickCheckScoreResult = {
  primaryArchetype: QuickCheckArchetype;
  tieOccurred: boolean;
  tiedArchetypes: QuickCheckArchetype[];
  displayArchetypeName: DisplayArchetypeName;
};

const ARCHETYPE_ORDER: QuickCheckArchetype[] = ["storm", "wall", "spark"];

export function isQuickCheckArchetype(value: unknown): value is QuickCheckArchetype {
  return value === "storm" || value === "wall" || value === "spark";
}

/** Majority wins; on tie, most-recent answer (last in array) wins for primary. Never null. */
export function scoreQuickCheckTally(
  answers: readonly QuickCheckArchetype[],
): QuickCheckScoreResult {
  if (answers.length === 0) {
    throw new Error("quickCheckTally must not be empty");
  }

  const counts: Record<QuickCheckArchetype, number> = {
    storm: 0,
    wall: 0,
    spark: 0,
  };
  for (const answer of answers) {
    counts[answer] += 1;
  }

  const max = Math.max(counts.storm, counts.wall, counts.spark);
  const leaders = ARCHETYPE_ORDER.filter((id) => counts[id] === max);
  const tieOccurred = leaders.length > 1;
  const primaryArchetype = tieOccurred
    ? ([...answers].reverse().find((a) => leaders.includes(a)) ?? leaders[0])
    : leaders[0];
  const tiedArchetypes = tieOccurred ? leaders : [];

  return {
    primaryArchetype,
    tieOccurred,
    tiedArchetypes,
    displayArchetypeName: resolveDisplayArchetypeName({
      primaryArchetype,
      tieOccurred,
      tiedArchetypes,
    }),
  };
}

export function resolveDisplayArchetypeName(args: {
  primaryArchetype: QuickCheckArchetype;
  tieOccurred: boolean;
  tiedArchetypes: readonly QuickCheckArchetype[];
}): DisplayArchetypeName {
  if (!args.tieOccurred) {
    if (args.primaryArchetype === "storm") return "Storm Child";
    if (args.primaryArchetype === "wall") return "Still Pond";
    return "Ember Child";
  }

  const set = new Set(args.tiedArchetypes);
  const hasStorm = set.has("storm");
  const hasWall = set.has("wall");
  const hasSpark = set.has("spark");

  if (hasStorm && hasWall && hasSpark) return "Weather Child";
  if (hasStorm && hasWall) return "Quiet Storm";
  if (hasStorm && hasSpark) return "Storm Child";
  if (hasWall && hasSpark) return "Ember Child";
  // Degenerate tie fallback — should not happen with valid tallies.
  if (args.primaryArchetype === "storm") return "Storm Child";
  if (args.primaryArchetype === "wall") return "Still Pond";
  return "Ember Child";
}

export { DISPLAY_ARCHETYPE_RESULT_COPY } from "./archetypeCaptionBank";
