// AUTO-GENERATED by sync-child-profile-module.js — do not edit by hand.
import type { ChildCompanionId } from "./tierAccess";
import type { RecentDeepCheckPoint } from "./archetypeDeepCheck";

export type { RecentDeepCheckPoint };

/**
 * Denormalized switcher list on users/{uid}.childrenSummary.
 * Written by createChildProfile + switchActiveChild (server-only).
 */
export type ChildrenSummaryEntry = {
  childId: string;
  name: string;
  companionId: ChildCompanionId;
  childOrder: number;
  /** Poetic Quick Check label when known (e.g. "Storm Child"). */
  displayArchetypeName?: string | null;
  /** Full years of age derived from DOB at write time. */
  ageYears?: number | null;
  /** ISO timestamp of last sanctuary visit / active switch. */
  lastVisitedAt?: string | null;
  /**
   * Shared Quick+Deep map trail (newest first, max 5).
   * Firestore key remains `recentDeepChecks` for compatibility.
   */
  recentDeepChecks?: RecentDeepCheckPoint[] | null;
};

/** Full calendar years between birth date and today. */
export function ageYearsFromBirthDate(birthDate: Date, today = new Date()): number {
  let years = today.getFullYear() - birthDate.getFullYear();
  const monthDelta = today.getMonth() - birthDate.getMonth();
  if (monthDelta < 0 || (monthDelta === 0 && today.getDate() < birthDate.getDate())) {
    years -= 1;
  }
  return years;
}

/** Parse ISO date string "YYYY-MM-DD" safely in local time. */
export function parseDobToDate(isoDate: string): Date | null {
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(isoDate.trim());
  if (!match) return null;
  const [, y, m, d] = match;
  const date = new Date(Number(y), Number(m) - 1, Number(d));
  if (Number.isNaN(date.getTime())) return null;
  return date;
}

export function ageYearsFromDob(dob: string, today = new Date()): number | null {
  const birth = parseDobToDate(dob);
  if (!birth) return null;
  const years = ageYearsFromBirthDate(birth, today);
  return years >= 0 && years < 130 ? years : null;
}

export function buildChildrenSummaryEntry(args: {
  childId: string;
  name: string;
  companionId: ChildCompanionId;
  childOrder: number;
  displayArchetypeName?: string | null;
  dob?: string | null;
  lastVisitedAt?: string | null;
  recentDeepChecks?: RecentDeepCheckPoint[] | null;
  today?: Date;
}): ChildrenSummaryEntry {
  const ageYears =
    typeof args.dob === "string" && args.dob.trim()
      ? ageYearsFromDob(args.dob, args.today ?? new Date())
      : null;
  return {
    childId: args.childId,
    name: args.name,
    companionId: args.companionId,
    childOrder: args.childOrder,
    displayArchetypeName: args.displayArchetypeName ?? null,
    ageYears,
    lastVisitedAt: args.lastVisitedAt ?? null,
    recentDeepChecks: args.recentDeepChecks ?? null,
  };
}

function startOfLocalDay(d: Date): Date {
  return new Date(d.getFullYear(), d.getMonth(), d.getDate());
}

function timeOfDayPhrase(hour: number): "morning" | "afternoon" | "evening" {
  if (hour < 12) return "morning";
  if (hour < 17) return "afternoon";
  return "evening";
}

/**
 * Warm relative label for journal cards — never technical timestamps.
 * Returns null when unknown so the UI can omit the line.
 */
export function formatLastExploredLabel(
  iso: string | null | undefined,
  now = new Date(),
): string | null {
  if (typeof iso !== "string" || !iso.trim()) return null;
  const then = new Date(iso);
  if (Number.isNaN(then.getTime())) return null;

  const dayMs = 24 * 60 * 60 * 1000;
  const todayStart = startOfLocalDay(now).getTime();
  const thenStart = startOfLocalDay(then).getTime();
  const dayDiff = Math.round((todayStart - thenStart) / dayMs);
  const tod = timeOfDayPhrase(then.getHours());

  if (dayDiff === 0) {
    if (tod === "morning") return "This morning";
    if (tod === "afternoon") return "This afternoon";
    return "This evening";
  }
  if (dayDiff === 1) {
    if (tod === "morning") return "Yesterday morning";
    if (tod === "afternoon") return "Yesterday afternoon";
    return "Yesterday evening";
  }
  if (dayDiff >= 2 && dayDiff <= 6) return "Earlier this week";
  if (dayDiff >= 7 && dayDiff <= 20) return "A little while ago";
  return "Some time ago";
}

export function stampLastVisited(
  summary: ChildrenSummaryEntry[],
  childId: string,
  atIso: string,
): ChildrenSummaryEntry[] {
  return summary.map((entry) =>
    entry.childId === childId ? { ...entry, lastVisitedAt: atIso } : entry,
  );
}
