// AUTO-GENERATED by sync-child-profile-module.js — do not edit by hand.
/**
 * Shared child-slot access helpers (CREATE_CHILD_PROFILE_PLAN.md §3).
 * Keep Firestore rules logic in parity with these functions.
 */

export const HARD_CHILD_CAP = 3;

export type ChildAccessTier = "free" | "wooden" | "fiberglass" | "lifetime";

export type AccountSubscriptionLike =
  | {
      subscriptionStatus?: string | null;
      isLifetime?: boolean | null;
    }
  | null
  | undefined;

/** Resolve account tier from existing subscription fields — no parallel subscriptionTier. */
export function resolveAccountTier(subscription: AccountSubscriptionLike): ChildAccessTier {
  if (subscription?.isLifetime === true) {
    return "lifetime";
  }
  const status = subscription?.subscriptionStatus;
  if (status === "wooden" || status === "fiberglass" || status === "free") {
    return status;
  }
  return "free";
}

export function tierChildLimit(tier: ChildAccessTier): number {
  switch (tier) {
    case "free":
      return 1;
    case "wooden":
    case "fiberglass":
    case "lifetime":
      return 3;
  }
}

/**
 * childOrder === 1 is always accessible — separate from the free-limit formula
 * so a missing/malformed subscription never locks out the grandfather child.
 */
export function canAccessChild(childOrder: number, tier: ChildAccessTier): boolean {
  if (childOrder === 1) {
    return true;
  }
  if (!Number.isFinite(childOrder) || childOrder < 1) {
    return false;
  }
  return childOrder <= tierChildLimit(tier);
}

export function canCreateNextChild(
  currentChildCount: number,
  tier: ChildAccessTier,
): { ok: true; nextOrder: number } | { ok: false; reason: "tier_limit" | "hard_cap" } {
  if (currentChildCount >= HARD_CHILD_CAP) {
    return { ok: false, reason: "hard_cap" };
  }
  if (currentChildCount >= tierChildLimit(tier)) {
    return { ok: false, reason: "tier_limit" };
  }
  return { ok: true, nextOrder: currentChildCount + 1 };
}

export const CHILD_COMPANION_IDS = ["blackbird", "goldfinch", "butterfly", "pond_fish"] as const;

export type ChildCompanionId = (typeof CHILD_COMPANION_IDS)[number];

export function isChildCompanionId(value: unknown): value is ChildCompanionId {
  return typeof value === "string" && (CHILD_COMPANION_IDS as readonly string[]).includes(value);
}

/** Pressed-flower interest allowlist — locked for v1 seal validation. */
export const CHILD_INTEREST_ALLOWLIST = [
  "curious",
  "gentle",
  "adventurous",
  "creative",
  "thoughtful",
  "playful",
] as const;

export type ChildInterestId = (typeof CHILD_INTEREST_ALLOWLIST)[number];

export function filterAllowedInterests(raw: unknown): ChildInterestId[] {
  if (!Array.isArray(raw)) return [];
  const allow = new Set<string>(CHILD_INTEREST_ALLOWLIST);
  const out: ChildInterestId[] = [];
  for (const item of raw) {
    if (typeof item !== "string") continue;
    if (!allow.has(item)) continue;
    if (out.includes(item as ChildInterestId)) continue;
    out.push(item as ChildInterestId);
    if (out.length >= 3) break;
  }
  return out;
}
